### ISSUE TITLE
Collection throws error on OSPFv2 facts Module

### ISSUE THREAD

**Issue by tweippert** [ansible-collections/cisco.ios#104]
##### SUMMARY
With the 1.0.0 Version of the Collection i get an error on my test system:

```
The full traceback is:
Traceback (most recent call last):
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 654, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/gather_facts.py", line 79, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 831, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 210, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 1249, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 1088, in _find_module_utils
    recursive_finder(module_name, remote_module_fqn, b_module_data, py_module_names,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 879, in recursive_finder
    recursive_finder(py_module_file[-1], next_fqn, py_module_cache[py_module_file][0],
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 724, in recursive_finder
    module_info = CollectionModuleInfo(py_module_name[-idx],
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 644, in __init__
    self.get_source()
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 660, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib/python3.8/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.cisco.ios.plugins.module_utils.network.ios.facts.ospfv2.ospfv2.__spec__ is None
fatal: [c3560-8p]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
The last working collection version on this system was 0.0.2!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /home/weiti/.ansible.cfg
  configured module search path = ['/home/weiti/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible
  executable location = /home/weiti/Develop/ansible-2.9.10/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### CONFIGURATION

```paste below
DEFAULT_LOG_PATH(/home/weiti/.ansible.cfg) = /home/weiti/ansible.log
HOST_KEY_CHECKING(/home/weiti/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/weiti/.ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/weiti/.ansible.cfg) = 60
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/weiti/.ansible.cfg) = 30
```

##### OS / ENVIRONMENT
Cisco WS-C3560-8PC-S
IOS 15.0(2)SE10a

##### STEPS TO REPRODUCE

```yaml
---
- name: Test Collection
  hosts: c3560-8p

  collections:
    - cisco.ios

  tasks:

  - name: Gather facts
    ios_facts:
      gather_subset:
        - min
```

##### EXPECTED RESULTS

``` 
TASK [Gather facts] ******************************************************************************************************************************************
task path: /home/weiti/Develop/test_collection.yml:10
<172.18.11.20> ESTABLISH LOCAL CONNECTION FOR USER: weiti
<172.18.11.20> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l `"&& mkdir /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698 && echo ansible-tmp-1594400719.6448686-1374667-237934044405698="` echo /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698 `" ) && sleep 0'
Using module file /home/weiti/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
<172.18.11.20> PUT /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/tmpq26advlu TO /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698/AnsiballZ_ios_facts.py
<172.18.11.20> EXEC /bin/sh -c 'chmod u+x /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698/ /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698/AnsiballZ_ios_facts.py && sleep 0'
<172.18.11.20> EXEC /bin/sh -c '/usr/bin/python /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698/AnsiballZ_ios_facts.py && sleep 0'
<172.18.11.20> EXEC /bin/sh -c 'rm -f -r /home/weiti/.ansible/tmp/ansible-local-137462898bwaa3l/ansible-tmp-1594400719.6448686-1374667-237934044405698/ > /dev/null 2>&1 && sleep 0'
ok: [c3560-8p] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "c3560-8p",
        "ansible_net_image": "flash:c3560-ipservicesk9-mz.150-2.SE10a.bin",
        "ansible_net_iostype": "IOS",
        "ansible_net_model": "WS-C3560-8PC",
        "ansible_net_python_version": "3.8.3",
        "ansible_net_serialnum": "FOC1524V1WC",
        "ansible_net_stacked_models": [
            "WS-C3560-8PC-S"
        ],
        "ansible_net_stacked_serialnums": [
            "FOC1524V1WC"
        ],
        "ansible_net_system": "ios",
        "ansible_net_version": "15.0(2)SE10a",
        "ansible_network_resources": {}
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_network_resources": null,
            "gather_subset": [
                "min"
            ],
            "provider": null
        }
    }
}
```

##### ACTUAL RESULTS

```paste below
TASK [Gathering Facts] ***************************************************************************************************************************************
task path: /home/weiti/Develop/test_collection.yml:2
[WARNING]: Ignoring timeout(10) for ios_facts
<172.18.11.20> ESTABLISH LOCAL CONNECTION FOR USER: weiti
<172.18.11.20> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/weiti/.ansible/tmp/ansible-local-1374746jf6_e7of `"&& mkdir /home/weiti/.ansible/tmp/ansible-local-1374746jf6_e7of/ansible-tmp-1594400763.946271-1374750-244032104406873 && echo ansible-tmp-1594400763.946271-1374750-244032104406873="` echo /home/weiti/.ansible/tmp/ansible-local-1374746jf6_e7of/ansible-tmp-1594400763.946271-1374750-244032104406873 `" ) && sleep 0'
<172.18.11.20> EXEC /bin/sh -c 'rm -f -r /home/weiti/.ansible/tmp/ansible-local-1374746jf6_e7of/ansible-tmp-1594400763.946271-1374750-244032104406873/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 654, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/gather_facts.py", line 79, in run
    res = self._execute_module(module_name=fact_module, module_args=mod_args, task_vars=task_vars, wrap_async=False)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 831, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/plugins/action/__init__.py", line 210, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, self._templar,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 1249, in modify_module
    (b_module_data, module_style, shebang) = _find_module_utils(module_name, b_module_data, module_path, module_args, task_vars, templar, module_compression,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 1088, in _find_module_utils
    recursive_finder(module_name, remote_module_fqn, b_module_data, py_module_names,
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 879, in recursive_finder
    recursive_finder(py_module_file[-1], next_fqn, py_module_cache[py_module_file][0],
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 724, in recursive_finder
    module_info = CollectionModuleInfo(py_module_name[-idx],
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 644, in __init__
    self.get_source()
  File "/home/weiti/Develop/ansible-2.9.10/lib/python3.8/site-packages/ansible/executor/module_common.py", line 660, in get_source
    data = pkgutil.get_data(to_native(self._package_name), to_native(self._mod_name + '.py'))
  File "/usr/lib/python3.8/pkgutil.py", line 619, in get_data
    spec = importlib.util.find_spec(package)
  File "/usr/lib/python3.8/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: ansible_collections.cisco.ios.plugins.module_utils.network.ios.facts.ospfv2.ospfv2.__spec__ is None
fatal: [c3560-8p]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}

```

**Comment by justjais** [comment]
@tweippert Thanks for raising the issue, but this seems to be Ansible core issue which is being discussed and addressed in the issue: https://github.com/ansible/ansible/issues/68361, also based on the conversation it seems that fix for the issue would be available in Ansible `2.9.11`, so for time being plz use the workaround mentioned in the issue: https://github.com/ansible/ansible/issues/68361#issuecomment-601740874 and if still unable to resolve the issue plz comment and follow up the discussion on the same with your use-case scenario.

Closing the bug as it's not IOS collection specific.

**Comment by tweippert** [comment]
With the workaround the following error shown up:

```
fatal: [c3560-8p]: FAILED! => {
    "msg": "Could not find imported module support code for ospfv2.  Looked for either NetworkTemplate.py or network_template.py"
}
```

Is this also core related?

**Comment by justjais** [comment]
@tweippert `network_template` is part of ansible netcommon collection (ref: https://galaxy.ansible.com/ansible/netcommon) can you plz check and verify if the netcomon collection is installed and the directory str. is as expected as well.

**Comment by tweippert** [comment]
@justjais Thanks for the hint, yes netcommon was installed, i reinstalled it again in version 1.0.0 and now the error disappears and the fact module is working again...
