### ISSUE TITLE
 ssh connect failed: kex error : no match for method kex algos: server [diffie-hellman-group1-sha1]

### ISSUE THREAD

**Issue by abdulet** [ansible-collections/cisco.ios#1133]
##### SUMMARY
Can't connect to devices which only support diffie-hellman-group1-sha1.
When running a command into these devices I get the error:
{"msg": "ssh connection failed: ssh connect failed: kex error : no match for method kex algos: server [diffie-hellman-group1-sha1], client [diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]"}

I tried many different options to solve this like:
- add settings into .ssh/config (Works for ssh from the system but not from ansible)
- add different ssh variables into ansible gloup_vars file: (ansible_ssh_extra_args: '-o KexAlgorithms="+diffie-hellman-group1-sha1"', ansible_ssh_common_args: '-o KexAlgorithms=+diffie-hellman-group1-sha1', ansible_ssh_args: '-o KexAlgorithms=+diffie-hellman-group1-sha1')
- added as an argument into ansible-playbook: --ssh-extra-args "-o KexAlgorithms=+diffie-hellman-group1-sha1" 

None of the above options worked, the playbook still fails with the same error message

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.11]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/SYNLAB/dcapa_admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/SYNLAB/dcapa_admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  5.3.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/inventory/netbox.yaml']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['host_list', 'netbox', 'yaml', 'constructed']
```

##### STEPS TO REPRODUCE
Create a backup playbook and try to execute it.

```yaml
  - name: Network Backup
    connection: ansible.netcommon.network_cli
    hosts: XXX
    gather_facts: false

    tasks:
       - name: Get configuration
          become: true
          become_method: enable
          cisco.ios.ios_command:
            commands: show running-config
          register: cli_output
```

##### EXPECTED RESULTS
The config output into cli_output variable

##### ACTUAL RESULTS
```paste below
TASK [Get configuration] *********************************************************************************************************************************************************************
task path: /home/XXX/netdevops/net_device_backups.yaml:28
Loading collection cisco.ios from /usr/lib/python3/dist-packages/ansible_collections/cisco/ios
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
included: /home/XXX/netdevops/tasks/cisco_ios_backup.yaml for YYY
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon

TASK [Get IOS running config] ****************************************************************************************************************************************************************
task path: /home/XXX/netdevops/tasks/cisco_ios_backup.yaml:1
Loading collection ansible.utils from /usr/lib/python3/dist-packages/ansible_collections/ansible/utils
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
<DEVICE_IP> attempting to start connection
<DEVICE_IP> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/bin/ansible-connection
<DEVICE_IP> found existing local domain socket, using it!
<DEVICE_IP> updating play_context for connection
<DEVICE_IP> invoked shell using ssh_type: libssh
<DEVICE_IP> Loading collection ansible.builtin from
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/cli/scripts/ansible_connection_cli_stub.py", line 322, in main
    conn.update_play_context(pc_data)
  File "/usr/lib/python3/dist-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
ansible.module_utils.connection.ConnectionError: ssh connection failed: ssh connect failed: kex error : no match for method kex algos: server [diffie-hellman-group1-sha1], client [diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]
fatal: [YYY]: FAILED! => {
    "msg": "ssh connection failed: ssh connect failed: kex error : no match for method kex algos: server [diffie-hellman-group1-sha1], client [diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]"
}
```

**Comment by itslychee** [comment]
I'm having a similar issue and the only way to fix it was setting values in `.ssh/config` which I really do not prefer for reproducibility reasons, and it seems like the module is ignoring anything I set in `all.vars` (inventory.yml) but I'm very new to ansible so I'm unsure if this is not an issue with me or not

**Comment by guy-silliman** [comment]
I am seeing the same issue. No way to get inventory based or environment variable based ssh options in to the connection process.

**Comment by Sauterelle** [comment]
I fix it by fallback to paramiko ssh_type connection.
Here is my ansible.cfg file : 
```
[defaults]
inventory = inventories/inventory.yml
host_key_checking = false
ask_pass=True

#ssh_args = -o KexAlgorithms=+diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1

[persistent_connection]
ssh_type = paramiko


[paramiko_connection]
look_for_keys=False
host_key_checking=False
remote_port=22
```
