### ISSUE TITLE
cisco.ios.ios_static_routes fails when 'no ip route-cache' configured on an interface

### ISSUE THREAD

**Issue by michalstaporek** [ansible-collections/cisco.ios#161]
##### SUMMARY

If 'no ip route-cache' is present in the config the playbook fails with following error:
invalid literal for int() with base 10: 'route-cache'
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_static_routes
##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/local/UK/michalstaporek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Sep 26 2019, 11:57:09) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT

WS-C3750X-48P-E running 15.2(4)E10

##### STEPS TO REPRODUCE

run the example 'gathered' task from the documention

```yaml
  - name: Gather listed static routes with provided configurations
    cisco.ios.ios_static_routes:
      config:
      state: gathered
```

##### EXPECTED RESULTS

We should receive a list of static routes configured on the device

##### ACTUAL RESULTS

Playbook fails

```paste below
TASK [Gather listed static routes with provided configurations] ********************************************************************
task path: /home/local/UK/michalstaporek/code/inv-ansible-cisco/static_routes.yaml:19
<192.168.60.60> ESTABLISH LOCAL CONNECTION FOR USER: UK\michalstaporek
<192.168.60.60> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9 `"&& mkdir /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978 && echo ansible-tmp-1601453949.562923-107586-82218039223978="` echo /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978 `" ) && sleep 0'
<mbvi-02a-sua1> Attempting python interpreter discovery
<192.168.60.60> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.60.60> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/local/UK/michalstaporek/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py
<192.168.60.60> PUT /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/tmphvxbi2q4 TO /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py
<192.168.60.60> EXEC /bin/sh -c 'chmod u+x /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/ /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py && sleep 0'
<192.168.60.60> EXEC /bin/sh -c '/usr/bin/python /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py && sleep 0'
<192.168.60.60> EXEC /bin/sh -c 'rm -f -r /home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py", line 102, in <module>
    _ansiballz_main()
  File "/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_static_routes', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py", line 692, in <module>
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py", line 687, in main
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py", line 91, in execute_module
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py", line 55, in get_static_routes_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 110, in get_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 69, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 146, in populate_destination
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 105, in update_netmask_to_cidr
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/utils/utils.py", line 282, in netmask_to_cidr
ValueError: invalid literal for int() with base 10: 'route-cache'
fatal: [mbvi-02a-sua1]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/local/UK/michalstaporek/.ansible/tmp/ansible-local-107513hlltjlc9/ansible-tmp-1601453949.562923-107586-82218039223978/AnsiballZ_ios_static_routes.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_static_routes', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py\", line 692, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py\", line 687, in main\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py\", line 91, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py\", line 55, in get_static_routes_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 110, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py\", line 69, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py\", line 146, in populate_destination\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py\", line 105, in update_netmask_to_cidr\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_Jm7wCX/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/utils/utils.py\", line 282, in netmask_to_cidr\nValueError: invalid literal for int() with base 10: 'route-cache'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by justjais** [comment]
@michalstaporek Thanks for raising the issue. I've raised PR to fix the issue you're facing, can you plz verify the PR fix and update if you're able to resolve the issue with the fix.

**Comment by michalstaporek** [comment]
Hello @justjais 
I have tested the fix and it works fine. Thank you very much. 
As a side note, I have got similar result by adding a whitespace after 'ip route', i.e.
line51:             "sh running-config | include ip route |ipv6 route"

**Comment by justjais** [comment]
@michalstaporek Thanks so much for your confirmation n not required to comment on the fix PR as you've confirmed here that with the fix it's working as expected for you.

Also, while changing the syntax I came across the suggested fix but went ahead with section implementation for having the std. out.

**Comment by justjais** [comment]
Fix already merged and released, hence closing the issue.
