### ISSUE TITLE
Parsing fails with VLANS that have "Remote" in their name

### ISSUE THREAD

**Issue by jrunu** [ansible-collections/cisco.ios#175]
##### SUMMARY

Gathering vlan facts fails with an exception if  vlans have the string "Remote" in their name.

https://github.com/ansible-collections/cisco.ios/blob/75d4269ec161ef36694e40903c82e450310d4bb1/plugins/module_utils/network/ios/facts/vlans/vlans.py#L72

I think looking for "Remote SPAN" instead could be specific enough. Also looking for "Type" is ambigous, looking at the output of "show vlans":

```
VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
[...]
VLAN Name                             Status    Ports
[...]
Primary Secondary Type              Ports
```

Name, Type and AREHops could probably be prefixed with a "VLAN "?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

IOS

##### STEPS TO REPRODUCE

```yaml
- hosts: ios
  gather_facts: False
  tasks:
    - ios_facts:
        gather_network_resources: vlans
```

##### EXPECTED RESULTS

Playbook retrieves vlan facts

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-local-2150jlM22y/ansible-tmp-1602570106.3-2157-261708818871745/AnsiballZ_ios_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-local-2150jlM22y/ansible-tmp-1602570106.3-2157-261708818871745/AnsiballZ_ios_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-local-2150jlM22y/ansible-tmp-1602570106.3-2157-261708818871745/AnsiballZ_ios_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.ios.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/modules/network/ios/ios_facts.py", line 235, in <module>
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/modules/network/ios/ios_facts.py", line 226, in main
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/module_utils/network/ios/facts/facts.py", line 68, in get_facts
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/module_utils/network/common/facts/facts.py", line 105, in get_network_resources_facts
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/module_utils/network/ios/facts/vlans/vlans.py", line 71, in populate_facts
  File "/tmp/ansible_ios_facts_payload_dxQc0O/ansible_ios_facts_payload.zip/ansible/module_utils/network/ios/facts/vlans/vlans.py", line 143, in render_config
ValueError: invalid literal for int() with base 10: '123  RemoteIsInMyName               active    Fa0/11'

```

**Comment by justjais** [comment]
@jrunu Thanks for logging the issue and it seems valid too, but can you edit your issue comment with all the required details, like expected and actual results for the failure config and the play as well.

**Comment by jrunu** [comment]
Report has been updated.

**Comment by justjais** [comment]
@jrunu Thanks so much for updating the issue, and the suggestion you made around ambiguity makes sense, I've implemented the suggested fix in the PR, can you plz verify and update if the PR fix resolves the issue you're facing.

**Comment by jrunu** [comment]
@justjais Confirmed,  with the changes it now collects the vlan facts without error. 

Followup Question:  I'm looking for which vlan is assigned to which interfaces. I collected interfaces  and vlans like so:

```
    - ios_facts:
       gather_network_resources:
          - interfaces
          - vlans
```
I dumped all variables and couldn't find that information. Is this information collected in any of the ressources options at all?

**Comment by justjais** [comment]
@jrunu Can u plz share the config for which you want the structured facts out

**Comment by jrunu** [comment]
@justjais Its actually available. I was looking for the l2_interfaces ressources. In there it says which interface has what vlans configured (access, voice, trunk).  I kinda assumed "interfaces" is the superset of "l3_interfaces" and "l2_interfaces". Thanks for fix.
