### ISSUE TITLE
ios_vlans module fails on ios.

### ISSUE THREAD

**Issue by ganeshrn** [ansible-collections/cisco.ios#18]
##### SUMMARY

ios_vlans module on classic ios fails with error 
```
line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: show vlan\r\n% Ambiguous command:  \"show vlan\"\r\nan-ios-02#\n",
```
as it is supported only on ios-l2.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_vlans
##### ANSIBLE VERSION

```paste below
2.9.6
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
  - name: collect vlan facts for ios
    ios_facts:
      gather_network_resources:
      - vlans
```

##### EXPECTED RESULTS

Module doc should reflect supported ios version and throw a user-readable error message for non-supported ios variants.

##### ACTUAL RESULTS

Throws error
```
line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: show vlan\r\n% Ambiguous command:  \"show vlan\"\r\nan-ios-02#\n",
```

```paste below

```

**Comment by IPvSean** [comment]
I have also hit this exact issue on AWS Cisco IOS (l3 only) Cisco IOS XE Software, Version 16.08.01a.  There is no `show vlan` command which creates a traceback->

```
TASK [grab info] ***************************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: rtr1#
fatal: [rtr1]: FAILED! => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/ec2-user/.ansible/tmp/ansible-local-18546GWi2uo/ansible-tmp-1599653685.8-154633073716813/AnsiballZ_ios_facts.py", line 102, in <module>
        _ansiballz_main()
      File "/home/ec2-user/.ansible/tmp/ansible-local-18546GWi2uo/ansible-tmp-1599653685.8-154633073716813/AnsiballZ_ios_facts.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/ec2-user/.ansible/tmp/ansible-local-18546GWi2uo/ansible-tmp-1599653685.8-154633073716813/AnsiballZ_ios_facts.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible.modules.network.ios.ios_facts', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
        fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/modules/network/ios/ios_facts.py", line 235, in <module>
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/modules/network/ios/ios_facts.py", line 226, in main
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/module_utils/network/ios/facts/facts.py", line 68, in get_facts
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/module_utils/network/common/facts/facts.py", line 105, in get_network_resources_facts
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/module_utils/network/ios/facts/vlans/vlans.py", line 56, in populate_facts
      File "/tmp/ansible_ios_facts_payload_C99O_e/ansible_ios_facts_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
    ansible.module_utils.connection.ConnectionError: show vlan
    show vlan
    % Incomplete command.

    rtr1#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

expected behavior should just have vlans: {} where its empty (b/c there is no L2 information)

on the actual router you can see the problem->
```
rtr1#show vlan
% Incomplete command.
```
whereas this works->
```
rtr1#show vlans

No Virtual LANs configured.
```

**Comment by IPvSean** [comment]
the problem is that I am trying to grab all facts->
```
---
- hosts: rtr1
  gather_facts: false
  tasks:

  - name: grab info
    ios_facts:
      gather_subset: min
      gather_network_resources: all

  - name: push structured data to hostvars
    copy:
      content: "{{ansible_network_resources | to_nice_yaml}}"
      dest: "{{playbook_dir}}/host_vars/{{inventory_hostname}}"
```
