### ISSUE TITLE
Using cisco.ios.ios_acls with replaced state will cause module to crash if ACL already exists.

### ISSUE THREAD

**Issue by ollylawrence** [ansible-collections/cisco.ios#230]
##### SUMMARY

Seems like using the replace state of the ACL module cisco.ios.ios_acls will cause the module to crash on a 2nd run.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_acls using state replace to create / replace standard ios ACL.

##### ANSIBLE VERSION

```paste below

ansible 2.9.16
  config file = /home/olly/.ansible.cfg
  configured module search path = [u'/home/olly/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### CONFIGURATION

```paste below

HOST_KEY_CHECKING(/home/olly/.ansible.cfg) = False

```

##### OS / ENVIRONMENT

[olly@centos7 ansible-builds-switches]$ cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

Switch is a cisco catalyst 3750 running IOS 15.0(2)SE11

##### STEPS TO REPRODUCE

```yaml

---

#simple acl test

- name: acltest.
  hosts: test-switch
  tasks:

  - name: relace acl test
    cisco.ios.ios_acls:
      state: replaced
      config:
      - afi: ipv4
        acls:
        - name: acls_TEST
          acl_type: standard
          aces:
          - grant: permit
            sequence: 10
            source:
              address: 192.168.1.1
          - grant: permit
            sequence: 20
            source:
              address: 10.0.0.1

```

##### EXPECTED RESULTS

ACL to be created on 1st run and on 2nd run the ACL to be replaced.

##### ACTUAL RESULTS

Module will create ACL upon 1st run but will crash on 2nd run:

Switch after 1st run:

ip access-list standard acls_TEST
 permit 10.0.0.1
 permit 192.168.1.1

2nd run the module crashes.

```paste below

1st RUN:

[olly@centos7 ansible-builds-switches]$ ansible-playbook -vvvv -i hosts.yml tests/acl-test.yml
ansible-playbook 2.9.16
  config file = /home/olly/.ansible.cfg
  configured module search path = [u'/home/olly/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /home/olly/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/olly/Documents/ansible-builds-switches/hosts.yml as it did not pass its verify_file() method
script declined parsing /home/olly/Documents/ansible-builds-switches/hosts.yml as it did not pass its verify_file() method
Parsed /home/olly/Documents/ansible-builds-switches/hosts.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: acl-test.yml ***********************************************************************************************
Positional arguments: tests/acl-test.yml
become_method: sudo
inventory: (u'/home/olly/Documents/ansible-builds-switches/hosts.yml',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in tests/acl-test.yml

PLAY [acltest.] ******************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /home/olly/Documents/ansible-builds-switches/tests/acl-test.yml:5
<test-switch> attempting to start connection
<test-switch> using connection plugin ansible.netcommon.network_cli
<test-switch> local domain socket does not exist, starting it
<test-switch> control socket path is /home/olly/.ansible/pc/8749158cbf
<test-switch> local domain socket listeners started successfully
<test-switch> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<test-switch>
<test-switch> local domain socket path is /home/olly/.ansible/pc/8749158cbf
[WARNING]: Ignoring timeout(10) for cisco.ios.ios_facts
<test-switch> ESTABLISH LOCAL CONNECTION FOR USER: olly
<test-switch> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG `"&& mkdir "` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250 `" && echo ansible-tmp-1611594068.95-53887-224765268211250="` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250 `" ) && sleep 0'
<test-switch> Attempting python interpreter discovery
<test-switch> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
<test-switch> PUT /home/olly/.ansible/tmp/ansible-local-53878La7xIG/tmpwPBj35 TO /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250/AnsiballZ_ios_facts.py
<test-switch> EXEC /bin/sh -c 'chmod u+x /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250/ /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250/AnsiballZ_ios_facts.py && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250/AnsiballZ_ios_facts.py && sleep 0'
<test-switch> EXEC /bin/sh -c 'rm -f -r /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594068.95-53887-224765268211250/ > /dev/null 2>&1 && sleep 0'
ok: [test-switch]
META: ran handlers

TASK [relace acl test] ***********************************************************************************************
task path: /home/olly/Documents/ansible-builds-switches/tests/acl-test.yml:9
<test-switch> attempting to start connection
<test-switch> using connection plugin ansible.netcommon.network_cli
<test-switch> found existing local domain socket, using it!
<test-switch> invoked shell using ssh_type: None
<test-switch> ssh type is set to paramiko
<test-switch> ssh connection done, setting terminal
<test-switch> loaded terminal plugin for network_os cisco.ios.ios
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> firing event: on_open_shell()
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> ssh connection has completed successfully
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> updating play_context for connection
<test-switch>
<test-switch> local domain socket path is /home/olly/.ansible/pc/8749158cbf
<test-switch> Using network group action cisco.ios.ios for cisco.ios.ios_acls
<test-switch> ESTABLISH LOCAL CONNECTION FOR USER: olly
<test-switch> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG `"&& mkdir "` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142 `" && echo ansible-tmp-1611594074.5-53926-87845759156142="` echo /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142 `" ) && sleep 0'
Using module file /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acls.py
<test-switch> PUT /home/olly/.ansible/tmp/ansible-local-53878La7xIG/tmpsELoaq TO /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142/AnsiballZ_ios_acls.py
<test-switch> EXEC /bin/sh -c 'chmod u+x /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142/ /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142/AnsiballZ_ios_acls.py && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142/AnsiballZ_ios_acls.py && sleep 0'
<test-switch> EXEC /bin/sh -c 'rm -f -r /home/olly/.ansible/tmp/ansible-local-53878La7xIG/ansible-tmp-1611594074.5-53926-87845759156142/ > /dev/null 2>&1 && sleep 0'
changed: [test-switch] => {
    "after": [
        {
            "acls": [
                {
                    "aces": [
                        {
                            "grant": "permit",
                            "sequence": 20,
                            "source": {
                                "address": "10.0.0.1"
                            }
                        },
                        {
                            "grant": "permit",
                            "sequence": 10,
                            "source": {
                                "address": "192.168.1.1"
                            }
                        }
                    ],
                    "acl_type": "standard",
                    "name": "acls_TEST"
                }
            ],
            "afi": "ipv4"
        }
    ],
    "before": [],
    "changed": true,
    "commands": [
        "ip access-list standard acls_TEST",
        "10 permit 192.168.1.1",
        "20 permit 10.0.0.1"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "acls": [
                        {
                            "aces": [
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "sequence": 10,
                                    "source": {
                                        "address": "192.168.1.1",
                                        "any": null,
                                        "host": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                },
                                {
                                    "destination": null,
                                    "dscp": null,
                                    "fragments": null,
                                    "grant": "permit",
                                    "log": null,
                                    "log_input": null,
                                    "option": null,
                                    "precedence": null,
                                    "protocol": null,
                                    "protocol_options": null,
                                    "sequence": 20,
                                    "source": {
                                        "address": "10.0.0.1",
                                        "any": null,
                                        "host": null,
                                        "port_protocol": null,
                                        "wildcard_bits": null
                                    },
                                    "time_range": null,
                                    "tos": null,
                                    "ttl": null
                                }
                            ],
                            "acl_type": "standard",
                            "name": "acls_TEST"
                        }
                    ],
                    "afi": "ipv4"
                }
            ],
            "running_config": null,
            "state": "replaced"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************
test-switch                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

2nd RUN:

[olly@centos7 ansible-builds-switches]$ ansible-playbook -vvvv -i hosts.yml tests/acl-test.yml
ansible-playbook 2.9.16
  config file = /home/olly/.ansible.cfg
  configured module search path = [u'/home/olly/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /home/olly/.ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /home/olly/Documents/ansible-builds-switches/hosts.yml as it did not pass its verify_file() method
script declined parsing /home/olly/Documents/ansible-builds-switches/hosts.yml as it did not pass its verify_file() method
Parsed /home/olly/Documents/ansible-builds-switches/hosts.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: acl-test.yml ***********************************************************************************************
Positional arguments: tests/acl-test.yml
become_method: sudo
inventory: (u'/home/olly/Documents/ansible-builds-switches/hosts.yml',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in tests/acl-test.yml

PLAY [acltest.] ******************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************
task path: /home/olly/Documents/ansible-builds-switches/tests/acl-test.yml:5
<test-switch> attempting to start connection
<test-switch> using connection plugin ansible.netcommon.network_cli
<test-switch> local domain socket does not exist, starting it
<test-switch> control socket path is /home/olly/.ansible/pc/33608f82d2
<test-switch> local domain socket listeners started successfully
<test-switch> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<test-switch>
<test-switch> local domain socket path is /home/olly/.ansible/pc/33608f82d2
[WARNING]: Ignoring timeout(10) for cisco.ios.ios_facts
<test-switch> ESTABLISH LOCAL CONNECTION FOR USER: olly
<test-switch> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK `"&& mkdir "` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798 `" && echo ansible-tmp-1611594085.64-53964-234956318530798="` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798 `" ) && sleep 0'
<test-switch> Attempting python interpreter discovery
<test-switch> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
<test-switch> PUT /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/tmpjKWGSq TO /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798/AnsiballZ_ios_facts.py
<test-switch> EXEC /bin/sh -c 'chmod u+x /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798/ /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798/AnsiballZ_ios_facts.py && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798/AnsiballZ_ios_facts.py && sleep 0'
<test-switch> EXEC /bin/sh -c 'rm -f -r /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594085.64-53964-234956318530798/ > /dev/null 2>&1 && sleep 0'
ok: [test-switch]
META: ran handlers

TASK [relace acl test] ***********************************************************************************************
task path: /home/olly/Documents/ansible-builds-switches/tests/acl-test.yml:9
<test-switch> attempting to start connection
<test-switch> using connection plugin ansible.netcommon.network_cli
<test-switch> found existing local domain socket, using it!
<test-switch> invoked shell using ssh_type: None
<test-switch> ssh type is set to paramiko
<test-switch> ssh connection done, setting terminal
<test-switch> loaded terminal plugin for network_os cisco.ios.ios
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> firing event: on_open_shell()
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> ssh connection has completed successfully
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> Response received, triggered 'persistent_buffer_read_timeout' timer of 0.1 seconds
<test-switch> updating play_context for connection
<test-switch>
<test-switch> local domain socket path is /home/olly/.ansible/pc/33608f82d2
<test-switch> Using network group action cisco.ios.ios for cisco.ios.ios_acls
<test-switch> ESTABLISH LOCAL CONNECTION FOR USER: olly
<test-switch> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK `"&& mkdir "` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380 `" && echo ansible-tmp-1611594091.27-54003-215664800709380="` echo /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380 `" ) && sleep 0'
Using module file /home/olly/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acls.py
<test-switch> PUT /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/tmpojl2j9 TO /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py
<test-switch> EXEC /bin/sh -c 'chmod u+x /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/ /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py && sleep 0'
<test-switch> EXEC /bin/sh -c '/usr/bin/python /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py && sleep 0'
<test-switch> EXEC /bin/sh -c 'rm -f -r /home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1410, in <module>
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py", line 1405, in main
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 82, in execute_module
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 127, in set_config
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 159, in set_state
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 227, in _state_replaced
  File "/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py", line 627, in split_set_cmd
ValueError: 'no' is not in list
fatal: [test-switch]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/olly/.ansible/tmp/ansible-local-53955XQdoyK/ansible-tmp-1611594091.27-54003-215664800709380/AnsiballZ_ios_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1410, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acls.py\", line 1405, in main\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 82, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 127, in set_config\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 159, in set_state\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 227, in _state_replaced\n  File \"/tmp/ansible_cisco.ios.ios_acls_payload_T2huJ9/ansible_cisco.ios.ios_acls_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acls/acls.py\", line 627, in split_set_cmd\nValueError: 'no' is not in list\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ***********************************************************************************************************
test-switch                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[olly@centos7 ansible-builds-switches]$

```

**Comment by ollylawrence** [comment]
Mea culpa, this is fixed the current development version 1.2.2-dev3 i was testing this in 1.2.1 closing.
