### ISSUE TITLE
cisco.ios.ios_vlans invalid literal for int() with base 10: 'Ports'

### ISSUE THREAD

**Issue by ibravo** [ansible-collections/cisco.ios#268]
##### SUMMARY
VLAN configuration failing on my Cisco 2960. Stripped configuration to bare minimum, just to gather facts from Vlans and module continues to fail. This seems similar to issues #202 and issue #237 , both closed without a resolution.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios.vlans

##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/it/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

OS: Ubuntu 20.04.2 LTS

SW Model: WS-C2960-48TT-S
SW Version: 15.0(2)SE11
SW Image: C2960-LANLITEK9-M   

##### STEPS TO REPRODUCE

Run a gather VLAN information script

This is the hosts file:

```
[all:vars]
# these defaults can be overridden for any grou in the [group:vas] section
ansible_connection=ansible.netcommon.network_cli
ansible_user=my_user
ansible_password=my_password

[cisco]
10.0.5.5

[cisco:vars]
ansible_network_os=cisco.ios.ios


```

And this is the playbook

```yaml
---
- name: Touch Cisco Switch
  hosts: cisco
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
    connection: network_cli

  tasks:
  - name: Get VLAN info
    cisco.ios.ios_vlans:
      config:
      state: gathered

```

##### EXPECTED RESULTS

Obtain information about the vlans configured in the switch

##### ACTUAL RESULTS

Playbook ends with error

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py", line 102, in <module>
    _ansiballz_main()
  File "/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 748, in <module>
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 743, in main
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 84, in execute_module
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 51, in get_vlans_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 121, in get_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 89, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 155, in render_config
ValueError: invalid literal for int() with base 10: 'Ports'
fatal: [10.0.5.5]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/it/.ansible/tmp/ansible-local-277177phtmcty0/ansible-tmp-1614986295.5050843-277181-225729733568475/AnsiballZ_ios_vlans.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 748, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 743, in main\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 84, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 51, in get_vlans_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 121, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 89, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_7tonydfg/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 155, in render_config\nValueError: invalid literal for int() with base 10: 'Ports'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by justjais** [comment]
@ibravo Thanks for logging the issue, can u plz share the config result for the `sh vlan` command.

**Comment by ibravo** [comment]
```
SW-2960-48T-2Flr-B#sh vlan
VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Gi0/2
5    Management_VLAN                  active    Fa0/2, Fa0/3
15   Second_Floor_VLAN                active    Fa0/1, Fa0/4, Fa0/5, Fa0/6, Fa0/7, Fa0/8, Fa0/9, Fa0/10, Fa0/11, Fa0/12
                                                Fa0/13, Fa0/14, Fa0/15, Fa0/16, Fa0/17, Fa0/18, Fa0/19, Fa0/20, Fa0/21
                                                Fa0/22, Fa0/23, Fa0/24, Fa0/25, Fa0/26, Fa0/27, Fa0/28, Fa0/29, Fa0/30
                                                Fa0/31, Fa0/32, Fa0/33, Fa0/34, Fa0/35, Fa0/36, Fa0/37, Fa0/38, Fa0/39
                                                Fa0/40, Fa0/41, Fa0/42, Fa0/43, Fa0/44, Fa0/45, Fa0/46, Fa0/47, Fa0/48
34   Wireless_VLAN                    active
40   Wireless_Guest_VLAN              active
1002 fddi-default                     act/unsup
1003 token-ring-default               act/unsup
1004 fddinet-default                  act/unsup
1005 trnet-default                    act/unsup

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        0      0
5    enet  100005     1500  -      -      -        -    -        0      0
15   enet  100015     1500  -      -      -        -    -        0      0
34   enet  100034     1500  -      -      -        -    -        0      0
40   enet  100040     1500  -      -      -        -    -        0      0
1002 fddi  101002     1500  -      -      -        -    -        0      0
1003 tr    101003     1500  -      -      -        -    -        0      0
1004 fdnet 101004     1500  -      -      -        ieee -        0      0
1005 trnet 101005     1500  -      -      -        ibm  -        0      0

Primary Secondary Type              Ports
------- --------- ----------------- ------------------------------------------

```
