### ISSUE TITLE
ios_acl_interfaces module throws 

### ISSUE THREAD

**Issue by ugarix** [ansible-collections/cisco.ios#279]
##### SUMMARY

I expect the ios_acl_interfaces module to apply an ACL to an interface but it throws out an error.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_acl_interfaces module with latest development build. (2.0.1-dev5)
##### ANSIBLE VERSION

```paste below
ansible 2.10.6
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/env/bin/ansible
  python version = 3.8.7 (default, Feb 19 2021, 15:35:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/vagrant/ansible/ansible.cfg) = ['/home/vagrant/ansible/hosts']
DEFAULT_STDOUT_CALLBACK(/home/vagrant/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/vagrant/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/vagrant/ansible/ansible.cfg) = /home/vagrant/env/bin/python3.8
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/vagrant/ansible/ansible.cfg) = 500
```

##### OS / ENVIRONMENT

controller centos 7.x, target os Cisco IOS XE Software, Version 16.06.04

##### STEPS TO REPRODUCE

I have a simple playbook with two tasks, the first task(ios_acls module) runs successfully and configures the ACL below on the router:
(env) [vagrant@server1 ansible]$ more host_vars/ios1/security_ACL.yml 
security_acls:
-   acls:
    -   aces:
        -   destination:
                any: true
                port_protocol:
                    eq: www
            grant: deny
            protocol: tcp
            sequence: 10
            source:
                any: true
        -   destination:
                any: true
                port_protocol:
                    eq: 22
            grant: deny
            protocol: tcp
            sequence: 20
            source:
                any: true
        -   destination:
                any: true
            grant: permit
            protocol: ip
            sequence: 30
            source:
                any: true
        acl_type: extended
        name: '110'
    afi: ipv4
But ios_acl_interfaces task throws out an unexpected error.

```yaml
---
- name: configure/audit VTY ACL 
  hosts: ios1
  gather_facts: no
  collections:
  - cisco.ios
  tasks:
  - name: acl config
    ios_acls:
      config: "{{ security_acls }}"
      state: replaced
  - name: apply ACL
    ios_acl_interfaces:
      config:
      - name: GigabitEthernet1
        access_groups:
          - afi: ipv4
            acls:
            - name: 110
              direction: in
      state: merged
```

##### ACTUAL RESULTS

```paste below
(env) [vagrant@server1 ansible]$ ansible-playbook acl110.yml -vvv
ansible-playbook 2.10.6
  config file = /home/vagrant/ansible/ansible.cfg
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/env/lib/python3.8/site-packages/ansible
  executable location = /home/vagrant/env/bin/ansible-playbook
  python version = 3.8.7 (default, Feb 19 2021, 15:35:05) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /home/vagrant/ansible/ansible.cfg as config file
host_list declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
script declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /home/vagrant/ansible/hosts as it did not pass its verify_file() method
Parsed /home/vagrant/ansible/hosts inventory source with ini plugin
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: acl110.yml ********************************************************************************************
1 plays in acl110.yml

PLAY [configure/audit VTY ACL] **********************************************************************************
META: ran handlers
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios

TASK [acl config] ***********************************************************************************************
task path: /home/vagrant/ansible/acl110.yml:8
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acls to cisco.ios.ios
<10.10.4.2> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<10.10.4.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842 `" && echo ansible-tmp-1616094560.8518026-3982-276498683415842="` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842 `" ) && sleep 0'
Using module file /home/vagrant/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acls.py
<10.10.4.2> PUT /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/tmp2zpg29wq TO /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842/AnsiballZ_ios_acls.py
<10.10.4.2> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842/ /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842/AnsiballZ_ios_acls.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c '/home/vagrant/env/bin/python3.8 /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842/AnsiballZ_ios_acls.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094560.8518026-3982-276498683415842/ > /dev/null 2>&1 && sleep 0'
[WARNING]: The value "22" (type int) was converted to "'22'" (type string). If this does not look like what you
expect, quote the entire value to ensure it does not change.
changed: [ios1] => changed=true 
  after:
  - acls:
    - aces:
      - destination:
          any: true
          port_protocol:
            eq: www
        grant: deny
        protocol: tcp
        sequence: 10
        source:
          any: true
      - destination:
          any: true
          port_protocol:
            eq: '22'
        grant: deny
        protocol: tcp
        sequence: 20
        source:
          any: true
      - destination:
          any: true
        grant: permit
        protocol: ip
        sequence: 30
        source:
          any: true
      acl_type: extended
      name: '101'
    - aces:
      - destination:
          any: true
          port_protocol:
            eq: www
        grant: deny
        protocol: tcp
        sequence: 10
        source:
          any: true
      - destination:
          any: true
          port_protocol:
            eq: '22'
        grant: deny
        protocol: tcp
        sequence: 20
        source:
          any: true
      - destination:
          any: true
        grant: permit
        protocol: ip
        sequence: 30
        source:
          any: true
      acl_type: extended
      name: '110'
    - acl_type: extended
      name: sil
    - aces:
      - destination:
          any: true
          port_protocol:
            eq: telnet
        grant: deny
        protocol: tcp
        sequence: 10
        source:
          host: 10.10.6.2
      - destination:
          any: true
        grant: permit
        protocol: ip
        sequence: 20
        source:
          any: true
      acl_type: extended
      name: vtyacl
    afi: ipv4
  before:
  - acls:
    - aces:
      - destination:
          any: true
          port_protocol:
            eq: www
        grant: deny
        protocol: tcp
        sequence: 10
        source:
          any: true
      - destination:
          any: true
          port_protocol:
            eq: '22'
        grant: deny
        protocol: tcp
        sequence: 20
        source:
          any: true
      - destination:
          any: true
        grant: permit
        protocol: ip
        sequence: 30
        source:
          any: true
      acl_type: extended
      name: '101'
    - acl_type: extended
      name: sil
    - aces:
      - destination:
          any: true
          port_protocol:
            eq: telnet
        grant: deny
        protocol: tcp
        sequence: 10
        source:
          host: 10.10.6.2
      - destination:
          any: true
        grant: permit
        protocol: ip
        sequence: 20
        source:
          any: true
      acl_type: extended
      name: vtyacl
    afi: ipv4
  commands:
  - ip access-list extended 110
  - 10 deny tcp any any eq www
  - 20 deny tcp any any eq 22
  - 30 permit ip any any
  invocation:
    module_args:
      config:
      - acls:
        - aces:
          - destination:
              address: null
              any: true
              host: null
              port_protocol:
                eq: www
                gt: null
                lt: null
                neq: null
                range: null
              wildcard_bits: null
            dscp: null
            evaluate: null
            fragments: null
            grant: deny
            log: null
            log_input: null
            option: null
            precedence: null
            protocol: tcp
            protocol_options: null
            sequence: 10
            source:
              address: null
              any: true
              host: null
              port_protocol: null
              wildcard_bits: null
            time_range: null
            tos: null
            ttl: null
          - destination:
              address: null
              any: true
              host: null
              port_protocol:
                eq: '22'
                gt: null
                lt: null
                neq: null
                range: null
              wildcard_bits: null
            dscp: null
            evaluate: null
            fragments: null
            grant: deny
            log: null
            log_input: null
            option: null
            precedence: null
            protocol: tcp
            protocol_options: null
            sequence: 20
            source:
              address: null
              any: true
              host: null
              port_protocol: null
              wildcard_bits: null
            time_range: null
            tos: null
            ttl: null
          - destination:
              address: null
              any: true
              host: null
              port_protocol: null
              wildcard_bits: null
            dscp: null
            evaluate: null
            fragments: null
            grant: permit
            log: null
            log_input: null
            option: null
            precedence: null
            protocol: ip
            protocol_options: null
            sequence: 30
            source:
              address: null
              any: true
              host: null
              port_protocol: null
              wildcard_bits: null
            time_range: null
            tos: null
            ttl: null
          acl_type: extended
          name: '110'
        afi: ipv4
      running_config: null
      state: replaced
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios

TASK [apply ACL] ************************************************************************************************
task path: /home/vagrant/ansible/acl110.yml:12
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_acl_interfaces to cisco.ios.ios
<10.10.4.2> ESTABLISH LOCAL CONNECTION FOR USER: vagrant
<10.10.4.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562 `" && echo ansible-tmp-1616094565.720805-4010-92047709988562="` echo /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562 `" ) && sleep 0'
Using module file /home/vagrant/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py
<10.10.4.2> PUT /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/tmpf81alfzh TO /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py
<10.10.4.2> EXEC /bin/sh -c 'chmod u+x /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/ /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c '/home/vagrant/env/bin/python3.8 /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py && sleep 0'
<10.10.4.2> EXEC /bin/sh -c 'rm -f -r /home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acl_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 598, in <module>
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 593, in main
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 76, in execute_module
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 126, in set_config
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 155, in set_state
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 229, in _state_merged
  File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 320, in _set_config
ValueError: dictionary update sequence element #0 has length 1; 2 is required
fatal: [ios1]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 102, in <module>
        _ansiballz_main()
      File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/vagrant/.ansible/tmp/ansible-local-39779isvh6_n/ansible-tmp-1616094565.720805-4010-92047709988562/AnsiballZ_ios_acl_interfaces.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_acl_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/local/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/local/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 598, in <module>
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_acl_interfaces.py", line 593, in main
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 76, in execute_module
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 126, in set_config
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 155, in set_state
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 229, in _state_merged
      File "/tmp/ansible_ios_acl_interfaces_payload_8cboan_x/ansible_ios_acl_interfaces_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/acl_interfaces/acl_interfaces.py", line 320, in _set_config
    ValueError: dictionary update sequence element #0 has length 1; 2 is required
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

PLAY RECAP ******************************************************************************************************
ios1                       : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(env) [vagrant@server1 ansible]$ 
(env) [vagrant@server1 ansible]$ 
```

**Comment by justjais** [comment]
@ugarix Thanks for logging the issue, but with the above information I am unable to reproduce the said issue, can you provide the result of `sh access-lists` to triage the issue further.

**Comment by KB-perByte** [comment]
@ugarix Closing as the issue is inactive
