### ISSUE TITLE
Switch cannot ping itself using ios_ping

### ISSUE THREAD

**Issue by aminvakil** [ansible-collections/cisco.ios#298]
##### SUMMARY
It fails with `AttributeError: 'NoneType' object has no attribute 'group'` error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_ping

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.3 (default, Apr  8 2021, 23:35:02) [GCC 10.2.0]
```

##### CONFIGURATION

```paste below
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
```

##### OS / ENVIRONMENT
Cisco SG300-28
Firmware Version:  1.3.0.62

##### STEPS TO REPRODUCE
`hosts`:
```
[switches]
192.168.1.254

[switches:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=ansible.netcommon.network_cli
ansible_become=yes
ansible_become_method=enable
ansible_user=cisco
```

```yaml
---
- name: ping
  ios_ping:
    dest: 192.168.1.254
```

##### EXPECTED RESULTS
Success

##### ACTUAL RESULTS
```paste below
ansible-playbook 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.3 (default, Apr  8 2021, 23:35:02) [GCC 10.2.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /root/cisco/hosts as it did not pass its verify_file() method
script declined parsing /root/cisco/hosts as it did not pass its verify_file() method
auto declined parsing /root/cisco/hosts as it did not pass its verify_file() method
Parsed /root/cisco/hosts inventory source with ini plugin
redirecting (type: modules) ansible.builtin.ios_ping to cisco.ios.ios_ping
Loading collection cisco.ios from /usr/lib/python3.9/site-packages/ansible_collections/cisco/ios
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.9/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: cisco.yml ************************************************************************************************************************************************************************************************************************
Positional arguments: cisco.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/root/cisco/hosts',)
forks: 5
1 plays in cisco.yml

PLAY [switches] ****************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [/root/cisco : ping] *********************************************************************************************************************************************************************************************
task path: /root/cisco/tasks/main.yml:2
Loading collection ansible.netcommon from /usr/lib/python3.9/site-packages/ansible_collections/ansible/netcommon
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<192.168.1.254> attempting to start connection
<192.168.1.254> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/bin/ansible-connection
<192.168.1.254> local domain socket does not exist, starting it
<192.168.1.254> control socket path is /root/.ansible/pc/1783180ca4
<192.168.1.254> Loading collection ansible.netcommon from /usr/lib/python3.9/site-packages/ansible_collections/ansible/netcommon
<192.168.1.254> Loading collection cisco.ios from /usr/lib/python3.9/site-packages/ansible_collections/cisco/ios
<192.168.1.254> local domain socket listeners started successfully
<192.168.1.254> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /usr/lib/python3.9/site-packages/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<192.168.1.254> 
<192.168.1.254> local domain socket path is /root/.ansible/pc/1783180ca4
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
<192.168.1.254> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.1.254> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-84898hhfdmf4 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025 `" && echo ansible-tmp-1618199961.176378-8492-96126484436025="` echo /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.ios_ping to cisco.ios.ios_ping
<192.168.1.254> Attempting python interpreter discovery
<192.168.1.254> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<192.168.1.254> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<192.168.1.254> Python interpreter discovery fallback (unable to get Linux distribution/version info)
Using module file /usr/lib/python3.9/site-packages/ansible_collections/cisco/ios/plugins/modules/ios_ping.py
<192.168.1.254> PUT /root/.ansible/tmp/ansible-local-84898hhfdmf4/tmpss0tw_9a TO /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py
<192.168.1.254> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/ /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py && sleep 0'
<192.168.1.254> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py && sleep 0'
<192.168.1.254> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_ping', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py", line 242, in <module>
  File "/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py", line 172, in main
  File "/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py", line 223, in parse_ping
AttributeError: 'NoneType' object has no attribute 'group'
[WARNING]: Platform linux on host 192.168.1.254 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
fatal: [192.168.1.254]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-84898hhfdmf4/ansible-tmp-1618199961.176378-8492-96126484436025/AnsiballZ_ios_ping.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_ping', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py\", line 242, in <module>\n  File \"/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py\", line 172, in main\n  File \"/tmp/ansible_ios_ping_payload_2cw_lg1y/ansible_ios_ping_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_ping.py\", line 223, in parse_ping\nAttributeError: 'NoneType' object has no attribute 'group'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by aminvakil** [comment]
Upgraded to 1.3.7.18 firmware and issue is still present.

**Comment by NilashishC** [comment]
cc @KB-perByte

**Comment by KB-perByte** [comment]
@aminvakil I tried reproducing the issue, but with the same configuration, it works just fine.
Why do you need  `ansible_become_method=enable` ?

**Comment by aminvakil** [comment]
@KB-perByte I can't reproduce this without `ansible_become_method=enable` as I don't have access to those switches anymore and I'm not sure why I had put it there.

Thanks for your response.
