### ISSUE TITLE
vtp version 2 will break ios_vlans 

### ISSUE THREAD

**Issue by benjdudas** [ansible-collections/cisco.ios#37]
##### SUMMARY

With vtp version set to 2 the  ios_vlans fails with following traceback:
```
"Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 472, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 467, in main\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 69, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 52, in get_interfaces_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 94, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 74, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 138, in render_config\nValueError: invalid literal for int() with base 10: 'Backup'\n"
```
Same thing with occur using `gather_network_resources: vlans` with `ios_facts`. Swiching to version 1 will correct the issue. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

./plugins/module_utils/network/ios/facts/vlans/vlans.py
##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
an-iosl2-01#show version
Cisco IOS Software, vios_l2 Software (vios_l2-ADVENTERPRISEK9-M), Experimental Version 15.2(20170321:233949) [mmen 101]
Copyright (c) 1986-2017 by Cisco Systems, Inc.
Compiled Wed 22-Mar-17 08:38 by mmen


ROM: Bootstrap program is IOSv

an-iosl2-01 uptime is 20 weeks, 5 days, 12 hours, 39 minutes
System returned to ROM by reload
System image file is "flash0:/vios_l2-adventerprisek9-m"
Last reload reason: Unknown reason



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco IOSv () processor (revision 1.0) with 734465K/50176K bytes of memory.
Processor board ID 9MUI61D7CNC
5 Gigabit Ethernet interfaces
DRAM configuration is 72 bits wide with parity disabled.
256K bytes of non-volatile configuration memory.
2097152K bytes of ATA System CompactFlash 0 (Read/Write)
0K bytes of ATA CompactFlash 1 (Read/Write)
0K bytes of ATA CompactFlash 2 (Read/Write)
10080K bytes of ATA CompactFlash 3 (Read/Write)

Configuration register is 0x101
```
```
an-iosl2-01#show vtp status
VTP Version capable             : 1 to 3
VTP version running             : 2
VTP Domain Name                 :
VTP Pruning Mode                : Disabled
VTP Traps Generation            : Disabled
Device ID                       : 5e00.0000.8000
Configuration last modified by 10.8.38.75 at 4-28-20 03:37:01
Local updater ID is 10.8.38.75 on interface Gi0/0 (first layer3 interface found)

Feature VLAN:
--------------
VTP Operating Mode                : Server
Maximum VLANs supported locally   : 1005
Number of existing VLANs          : 10
Configuration Revision            : 14
MD5 digest                        : 0xB1 0x7B 0x0D 0x99 0x9F 0x19 0xA1 0xF8
                                    0xFC 0xA6 0xD8 0x83 0x80 0x76 0x5A 0x52
```

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: add test vlan
      cisco.ios.ios_vlans:
        config:
          - name: vlan_test
            vlan_id: 330
            state: active
            shutdown: disabled
        state: merged
```

##### ACTUAL RESULTS

```paste below
ansible-playbook 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /root/ios-facts/hosts as it did not pass its verify_file() method
script declined parsing /root/ios-facts/hosts as it did not pass its verify_file() method
auto declined parsing /root/ios-facts/hosts as it did not pass its verify_file() method
Parsed /root/ios-facts/hosts inventory source with ini plugin

PLAYBOOK: ios-vlans.yml *****************************************************************************
1 plays in ios-vlans.yml

PLAY [ec2_cisco_xe] *********************************************************************************
META: ran handlers

TASK [add test vlan] ********************************************************************************
task path: /root/ios-facts/ios-vlans.yml:6
<10.8.38.75> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.8.38.75> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-26914clklL4 `"&& mkdir /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206 && echo ansible-tmp-1589219024.96-26923-82174175600206="` echo /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206 `" ) && sleep 0'
<10.8.38.75> Attempting python interpreter discovery
<10.8.38.75> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.8.38.75> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py
<10.8.38.75> PUT /root/.ansible/tmp/ansible-local-26914clklL4/tmpsoqotu TO /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py
<10.8.38.75> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/ /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py && sleep 0'
<10.8.38.75> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py && sleep 0'
<10.8.38.75> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 472, in <module>
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py", line 467, in main
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 69, in execute_module
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py", line 52, in get_interfaces_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 94, in get_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 74, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py", line 138, in render_config
ValueError: invalid literal for int() with base 10: 'Backup'
fatal: [10.8.38.75]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-26914clklL4/ansible-tmp-1589219024.96-26923-82174175600206/AnsiballZ_ios_vlans.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_vlans', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 472, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_vlans.py\", line 467, in main\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 69, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/vlans/vlans.py\", line 52, in get_interfaces_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 94, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 74, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_vlans_payload_ybCUzk/ansible_cisco.ios.ios_vlans_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/vlans/vlans.py\", line 138, in render_config\nValueError: invalid literal for int() with base 10: 'Backup'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ******************************************************************************************
10.8.38.75                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by benjdudas** [comment]
Downstream issue: https://github.com/ansible/ansible/issues/68147

**Comment by benjdudas** [comment]
***##`show vlan` vtp v1:***
```
an-iosl2-01#show vlan

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Gi0/2
10   VLAN0010                         active    Gi0/1
20   VLAN0020                         active
30   VLAN0030                         active
40   VLAN0040                         active
110  110                              active
330  vlan_test                        active
1002 fddi-default                     act/unsup
1003 token-ring-default               act/unsup
1004 fddinet-default                  act/unsup
1005 trnet-default                    act/unsup

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        0      0
10   enet  100010     1500  -      -      -        -    -        0      0
20   enet  100020     1500  -      -      -        -    -        0      0
30   enet  100030     1500  -      -      -        -    -        0      0
40   enet  100040     1500  -      -      -        -    -        0      0
110  enet  100110     1500  -      -      -        -    -        0      0
330  enet  100330     1500  -      -      -        -    -        0      0
1002 fddi  101002     1500  -      -      -        -    -        0      0
1003 tr    101003     1500  -      -      -        -    -        0      0
1004 fdnet 101004     1500  -      -      -        ieee -        0      0
1005 trnet 101005     1500  -      -      -        ibm  -        0      0

Remote SPAN VLANs
------------------------------------------------------------------------------


Primary Secondary Type              Ports
------- --------- ----------------- ------------------------------------------
```
***##`show vlan` vtp v2:***
```
an-iosl2-01#show vlan

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Gi0/2
10   VLAN0010                         active    Gi0/1
20   VLAN0020                         active
30   VLAN0030                         active
40   VLAN0040                         active
110  110                              active
330  vlan_test                        active
1002 fddi-default                     act/unsup
1003 trcrf-default                    act/unsup
1004 fddinet-default                  act/unsup
1005 trbrf-default                    act/unsup

VLAN Type  SAID       MTU   Parent RingNo BridgeNo Stp  BrdgMode Trans1 Trans2
---- ----- ---------- ----- ------ ------ -------- ---- -------- ------ ------
1    enet  100001     1500  -      -      -        -    -        0      0
10   enet  100010     1500  -      -      -        -    -        0      0
20   enet  100020     1500  -      -      -        -    -        0      0
30   enet  100030     1500  -      -      -        -    -        0      0
40   enet  100040     1500  -      -      -        -    -        0      0
110  enet  100110     1500  -      -      -        -    -        0      0
330  enet  100330     1500  -      -      -        -    -        0      0
1002 fddi  101002     1500  -      -      -        -    -        0      0
1003 trcrf 101003     4472  1005   3276   -        -    srb      0      0
1004 fdnet 101004     1500  -      -      -        ieee -        0      0
1005 trbrf 101005     4472  -      -      15       ibm  -        0      0


VLAN AREHops STEHops Backup CRF
---- ------- ------- ----------
1003 7       7       off

Remote SPAN VLANs
------------------------------------------------------------------------------


Primary Secondary Type              Ports
------- --------- ----------------- ------------------------------------------
```

**Comment by benjdudas** [comment]
***Can get around this error by replacing:***
```config["mtu"] = int(conf[3])```
***As:***
```config["mtu"] = str(conf[3])```

https://github.com/ansible-collections/cisco.ios/blob/2c697125703dd4ba550c2420ec3e225bd0028d67/plugins/module_utils/network/ios/facts/vlans/vlans.py#L138
