### ISSUE TITLE
ios_l2_interfaces in replaced mode fails on fresh ports

### ISSUE THREAD

**Issue by justjais** [ansible-collections/cisco.ios#44]
##### SUMMARY

Attempt to run playbook fails with exception if pruning not defined

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_l2_interfaces
may be related to https://github.com/ansible/ansible/issues/65032, as it works if port mode defined.

##### ANSIBLE VERSION

```paste below
~/network-ansible$ ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'user path hidden', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Cisco WS-C3750X-48 running 15.2(4)E1

##### STEPS TO REPRODUCE

Run below playbook against fresh port, that has no configuration yet:
interface GigabitEthernet1/0/13
!

However, if replaced changed to merged, module works as expected.

```yaml
- name: Replaces device configuration of listed l2 interfaces with provided configuration
  ios_l2_interfaces:
    config:
      - name: GigabitEthernet0/2
        trunk:
        - allowed_vlan: 20-25,40
          native_vlan: 20
          encapsulation: dot1q
    state: replaced
```

##### EXPECTED RESULTS

Successful port configuration

##### ACTUAL RESULTS

Module though an error

```paste below
The full traceback is:
Traceback (most recent call last):
...
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/modules/network/ios/ios_l2_interfaces.py", line 364, in <module>
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/modules/network/ios/ios_l2_interfaces.py", line 359, in main
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py", line 63, in execute_module
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py", line 88, in set_config
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py", line 113, in set_state
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/module_utils/network/ios/config/l2_interfaces/l2_interfaces.py", line 134, in _state_replaced
  File "/tmp/ansible_ios_l2_interfaces_payload_DjCV5p/ansible_ios_l2_interfaces_payload.zip/ansible/module_utils/network/ios/utils/utils.py", line 75, in filter_dict_having_none_value
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by justjais** [comment]
PR to fix the issue is raised, once merged the issue will be resolved. Thus, closing the issue.
