### ISSUE TITLE
Attempting to use ios_banner results in a IndexError on AWX 19.4.0

### ISSUE THREAD

**Issue by ZachHoiberg** [ansible-collections/cisco.ios#447]
##### SUMMARY
Trying to set a Banner using cisco.ios.ios_banner results in an IndexError

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_banner

##### ANSIBLE VERSION
```
 [core 2.11.6.post0] 
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```
This is on my default AWX EE
# /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              1.5.0
ansible.posix           1.3.0
ansible.windows         1.7.2
awx.awx                 19.2.2
azure.azcollection      1.9.0
community.vmware        1.14.0
google.cloud            1.0.2
kubernetes.core         2.1.1
openstack.cloud         1.5.1
ovirt.ovirt             1.6.2
redhatinsights.insights 1.0.5
theforeman.foreman      2.2.0
```
I additionally have the following in my requirements.yml:
```
---
collections:
# Install community.kubernetes Ansible Collection
- name: community.kubernetes
  source: https://galaxy.ansible.com
  
- name: cisco.ios

- name: ansible.windows
  source: https://galaxy.ansible.com

- name: ansible.netcommon
  source: https://galaxy.ansible.com/
```

##### CONFIGURATION
default, no config file.

##### OS / ENVIRONMENT
Target: 15.2(2)E9 WS-C2960S-24TS-L 
Host: AWX 19.4 deployed via AWX Operator, Ubuntu Server 20.04

##### STEPS TO REPRODUCE
Other IOS commands work, but ios_banner fails. I simply ran the following below against that 2960 host.

```yaml
    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
```

##### EXPECTED RESULTS
A banner is applied to the switch

##### ACTUAL RESULTS
The banner is not applied and an error is shown.

```
redirecting (type: action) cisco.ios.ios_banner to cisco.ios.ios

TASK [Configure the login banner] **********************************************
task path: /runner/project/IOS-NDM-STIG.yml:49
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_banner to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_banner to cisco.ios.ios
<10.1.151.70> ESTABLISH LOCAL CONNECTION FOR USER: runner
<10.1.151.70> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp/ansible-local-21xr3n9hni `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874 `" && echo ansible-tmp-1634823448.1078465-127-255341896225874="` echo /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874 `" ) && sleep 0'
Using module file /runner/requirements_collections/ansible_collections/cisco/ios/plugins/modules/ios_banner.py
<10.1.151.70> PUT /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/tmpmrifro1q TO /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py
<10.1.151.70> EXEC /bin/sh -c 'chmod u+x /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/ /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py && sleep 0'
<10.1.151.70> EXEC /bin/sh -c '/usr/bin/python3 /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py && sleep 0'
<10.1.151.70> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py", line 100, in <module>
    _ansiballz_main()
  File "/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_banner', init_globals=dict(_module_fqn='ansible_collections.cisco.ios.plugins.modules.ios_banner', _modlib_path=modlib_path),
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py", line 207, in <module>
  File "/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py", line 196, in main
  File "/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py", line 150, in map_config_to_obj
IndexError: list index out of range
fatal: [10.1.151.70]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py\\", line 100, in <module>\\n    _ansiballz_main()\\n  File \\"/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py\\", line 92, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/home/runner/.ansible/tmp/ansible-local-21xr3n9hni/ansible-tmp-1634823448.1078465-127-255341896225874/AnsiballZ_ios_banner.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_banner', init_globals=dict(_module_fqn='ansible_collections.cisco.ios.plugins.modules.ios_banner', _modlib_path=modlib_path),\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 207, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\\", line 207, in <module>\\n  File \\"/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\\", line 196, in main\\n  File \\"/tmp/ansible_cisco.ios.ios_banner_payload_ky36if8i/ansible_cisco.ios.ios_banner_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_banner.py\\", line 150, in map_config_to_obj\\nIndexError: list index out of range\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
10.1.151.70                : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by KB-perByte** [comment]
Hey @ZachHoiberg, 
Can you please try enabling the option `ansible_network_import_modules` which can be specified in the inventory
Looks like it's unable to resolve the module properly. As suggested can you try the below option in your inventory, applied to all network appliances based hosts
```
[all:vars]
ansible_network_import_modules=True
```

Thanks

**Comment by ZachHoiberg** [comment]
@KB-perByte 

I had recently updated to AWX 19.5.0 due to some errors we were seeing with importing roles, and it appears that that update also fixed the banner issue I had previously. 

It is now working without any modification to the inventory on my part, but I'm not sure what exactly has changed between 19.4.0 and 19.5.0 that caused this.

Thank you for your help with this.
