### ISSUE TITLE
ios_banner breaks with first line chars

### ISSUE THREAD

**Issue by pffs** [ansible-collections/cisco.ios#50]
##### SUMMARY

If a banner contains characters on the first line before the line break, `ios_banner` crashes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ios_banner`

##### ANSIBLE VERSION

```paste below
ansible 2.9.4
  config file = /home/arantz/change-scripts/ansible/ansible.cfg
  configured module search path = ['/home/arantz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/arantz/change-scripts/ansible/venv3/lib/python3.6/site-packages/ansible
  executable location = /home/arantz/change-scripts/ansible/venv3/bin/ansible
  python version = 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/arantz/change-scripts/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/arantz/change-scripts/ansible/ansible.cfg) = ['timer', 'json_result']
DEFAULT_FORKS(/home/arantz/change-scripts/ansible/ansible.cfg) = 45
DEFAULT_HOST_LIST(/home/arantz/change-scripts/ansible/ansible.cfg) = ['/home/arantz/change-scripts/ansible/inventories']
DEFAULT_LOCAL_TMP(/home/arantz/change-scripts/ansible/ansible.cfg) = /home/arantz/.ansible/tmp/ansible-local-16723s58fhpxr
DEFAULT_LOG_PATH(/home/arantz/change-scripts/ansible/ansible.cfg) = /home/arantz/change-scripts/ansible/logs/log
HOST_KEY_CHECKING(/home/arantz/change-scripts/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/arantz/change-scripts/ansible/ansible.cfg) = auto_silent
PERSISTENT_COMMAND_TIMEOUT(/home/arantz/change-scripts/ansible/ansible.cfg) = 120
PERSISTENT_CONNECT_TIMEOUT(/home/arantz/change-scripts/ansible/ansible.cfg) = 90
```

##### OS / ENVIRONMENT

Ubuntu 18.04 against Cisco IOS

##### STEPS TO REPRODUCE

```yaml
- ios_banner:
    banner: login
    text: "test"
    state: present
```
Banner looks like:
```
banner login ^CC
Login banner
^C
```
Note the extra C (this is very common on restored configurations as people tend to forget to remove it when pasting in an old config)

##### EXPECTED RESULTS

Banner should be updated

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py", line 186, in <module>
  File "/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py", line 171, in main
  File "/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py", line 127, in map_config_to_obj
IndexError: list index out of range

fatal: [router]: FAILED! => {
  "changed": false,
  "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py\", line 186, in <module>\n  File \"/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py\", line 171, in main\n  File \"/tmp/ansible_ios_banner_payload_gn_g72hu/ansible_ios_banner_payload.zip/ansible/modules/network/ios/ios_banner.py\", line 127, in map_config_to_obj\nIndexError: list index out of range\n",
  "module_stdout": "",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1
}
```
I attempted to backport ios_banner back into 2.9 so that I could use the functionality from https://github.com/ansible/ansible/pull/62573 and got a crash. This is still an issue with the current code.

The issue is on lines https://github.com/ansible-collections/cisco.ios/blob/master/plugins/modules/ios_banner.py#L126-L128

It is not using the same string to match against as it is to split against, so if there any characters between the banner `^C` start delimiter and the first new line, you get an `IndexError`.

In my particular scenario, the extra `C` is an error, and I corrected it by adding in a `.*` for extra characters and then using the searches results to split:
```python
    if out:
        regex = 'banner ' + module.params["banner"] + ' \^C.*\n'
        matches = search(regex, out, M)
        if matches:
            output = str((out.split(matches[0]))[1].split("^C\n")[0])
        else:
            output = None
```

This doesn't allow for someone intentionally not having a newline at the beginning of the banner, but it does at least prevent it from tracing back. As per above, the extra Cs are a very common side effect of restoring a configuration.

**Comment by rohitthakur2590** [comment]
@pffs 
Thank you very much for your interest in Ansible. 
You are right, will push a patch for this.
Thanks

**Comment by lotaris-xx** [comment]
Bumped into this yesterday with ^CC in the device config. Any ETA on a patch?
