### ISSUE TITLE
ios_facts: errors line 255, in populate_ipv4_interfaces\nKeyError: 'IP'\n

### ISSUE THREAD

**Issue by lvbernus** [ansible-collections/cisco.ios#593]
##### SUMMARY

Getting Error `KeyError: 'IP'` when running ios_facts against Cisco SG350 and SG250 switches.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_facts

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.6]                                                                                          
  config file = /home/luis/ansible/ansible.cfg                                                                 
  configured module search path = ['/home/luis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible                                      
  ansible collection location = /home/luis/.ansible/collections:/usr/share/ansible/collections                 
  executable location = /usr/bin/ansible                                                                       
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]                                         
  jinja version = 3.1.2                                                                                        
  libyaml = True                                                                                               
```
and
```paste below
ansible [core 2.14.0.dev0] (devel 9f7956ba30) last updated 2022/05/30 13:50:47 (GMT +200)
  config file = /home/luis/ansible/ansible.cfg
  configured module search path = ['/home/luis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/luis/ansible/ansible/lib/ansible
  ansible collection location = /home/luis/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/luis/ansible/ansible/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True                                                                                        
```
##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  2.8.1
```

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/home/user/ansible/ansible.cfg) = ['/home/user/ansible/hosts.yml']
```

##### OS / ENVIRONMENT

Host: Ubuntu 20.04.4 LTS
Switch: Cisco SG350X-48P
Firmware: 2.5.8.15

##### STEPS TO REPRODUCE

hosts.yml:
```yaml
all:
  children:
    switches:
      children:
        sg350:
          hosts:
            sw-test.test.local:
      vars:
        ansible_network_os: ios
        ansible_connection: network_cli
        ansible_user: ctrit
        ansible_ssh_private_key_file: /home/user/.ssh/sgnet_id_rsa
```
playbook.yml

```yaml
---
- name: Network config with cisco SG350
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: sg350
  tasks:
    - name: Get config for iOS device
      ios_facts:
        gather_subset: all
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
```
Then run ` ansible-playbook playbook.yml`

##### EXPECTED RESULTS

```
PLAY [Network config with cisco SG350]
***************************************************************************************************************************

TASK [Get config for iOS device]
***************************************************************************************************************************
ok: [sw-test.test.local]

TASK [Display the config]
***************************************************************************************************************************
ok: [sw-test.test.local] => {
    "msg": "The hostname is sw-test and the OS is xxx"
}
```
##### ACTUAL RESULTS

```paste below
2022-05-30 14:45:42,607 p=564245 u=user n=ansible | ansible-playbook [core 2.12.6]
  config file = /home/user/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
2022-05-30 14:45:42,607 p=564245 u=user n=ansible | Using /home/user/ansible/ansible.cfg as config file
2022-05-30 14:45:42,607 p=564245 u=user n=ansible | setting up inventory plugins
2022-05-30 14:45:42,611 p=564245 u=user n=ansible | host_list declined parsing /home/user/ansible/hosts.yml as it did not pass its verify_file() method
2022-05-30 14:45:42,611 p=564245 u=user n=ansible | script declined parsing /home/user/ansible/hosts.yml as it did not pass its verify_file() method
2022-05-30 14:45:42,614 p=564245 u=user n=ansible | Parsed /home/user/ansible/hosts.yml inventory source with yaml plugin
2022-05-30 14:45:42,718 p=564245 u=user n=ansible | redirecting (type: modules) ansible.builtin.ios_facts to cisco.ios.ios_facts
2022-05-30 14:45:42,719 p=564245 u=user n=ansible | Loading collection cisco.ios from /usr/lib/python3/dist-packages/ansible_collections/cisco/ios
2022-05-30 14:45:42,722 p=564245 u=user n=ansible | Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py
2022-05-30 14:45:42,730 p=564245 u=user n=ansible | Skipping callback 'default', as we already have a stdout callback.
2022-05-30 14:45:42,730 p=564245 u=user n=ansible | Skipping callback 'minimal', as we already have a stdout callback.
2022-05-30 14:45:42,730 p=564245 u=user n=ansible | Skipping callback 'oneline', as we already have a stdout callback.
2022-05-30 14:45:42,730 p=564245 u=user n=ansible | PLAYBOOK: playbook.yml ********************************************************************************************************************************************************************************************************************************************
2022-05-30 14:45:42,730 p=564245 u=user n=ansible | 1 plays in playbook.yml
2022-05-30 14:45:42,732 p=564245 u=user n=ansible | PLAY [Network config with cisco SG350] ************************************************************************************************************************************************************************************************************************
2022-05-30 14:45:42,740 p=564245 u=user n=ansible | META: ran handlers
2022-05-30 14:45:42,745 p=564245 u=user n=ansible | TASK [Get config for iOS device] ******************************************************************************************************************************************************************************************************************************
2022-05-30 14:45:42,750 p=564250 u=user n=ansible | redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
2022-05-30 14:45:42,752 p=564250 u=user n=ansible | Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon
2022-05-30 14:45:42,774 p=564250 u=user n=ansible | redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:42,776 p=564250 u=user n=ansible | redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:42,780 p=564250 u=user n=ansible | <sw-test.test.local> attempting to start connection
2022-05-30 14:45:42,780 p=564250 u=user n=ansible | <sw-test.test.local> using connection plugin ansible.netcommon.network_cli
2022-05-30 14:45:42,780 p=564250 u=user n=ansible | Found ansible-connection at path /usr/bin/ansible-connection
2022-05-30 14:45:43,093 p=564257 u=user n=ansible | redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
2022-05-30 14:45:43,095 p=564257 u=user n=ansible | Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon
2022-05-30 14:45:43,116 p=564257 u=user n=ansible | redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,119 p=564257 u=user n=ansible | Loading collection cisco.ios from /usr/lib/python3/dist-packages/ansible_collections/cisco/ios
2022-05-30 14:45:43,121 p=564257 u=user n=ansible | redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> local domain socket does not exist, starting it
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> control socket path is /home/user/.ansible/pc/1201fbdd7d
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> Loading collection ansible.netcommon from /usr/lib/python3/dist-packages/ansible_collections/ansible/netcommon
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> redirecting (type: terminal) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> Loading collection cisco.ios from /usr/lib/python3/dist-packages/ansible_collections/cisco/ios
2022-05-30 14:45:43,167 p=564250 u=user n=ansible | <sw-test.test.local> redirecting (type: cliconf) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | <sw-test.test.local> local domain socket listeners started successfully
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | <sw-test.test.local> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /usr/lib/python3/dist-packages/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os ios
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | network_os is set to ios
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | <sw-test.test.local> ssh type is set to paramiko
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | <sw-test.test.local> 
2022-05-30 14:45:43,168 p=564250 u=user n=ansible | <sw-test.test.local> local domain socket path is /home/user/.ansible/pc/1201fbdd7d
2022-05-30 14:45:43,174 p=564250 u=user n=ansible | redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,174 p=564250 u=user n=ansible | <sw-test.test.local> Using network group action ios for ios_facts
2022-05-30 14:45:43,175 p=564250 u=user n=ansible | redirecting (type: action) ansible.builtin.ios to cisco.ios.ios
2022-05-30 14:45:43,183 p=564250 u=user n=ansible | <sw-test.test.local> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
2022-05-30 14:45:43,183 p=564250 u=user n=ansible | <sw-test.test.local> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
2022-05-30 14:45:43,183 p=564250 u=user n=ansible | <sw-test.test.local> ESTABLISH LOCAL CONNECTION FOR USER: user
2022-05-30 14:45:43,183 p=564250 u=user n=ansible | <sw-test.test.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-local-564245yil8i4kr `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863 `" && echo ansible-tmp-1653914743.183508-564250-123580383287863="` echo /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863 `" ) && sleep 0'
2022-05-30 14:45:43,188 p=564250 u=user n=ansible | redirecting (type: modules) ansible.builtin.ios_facts to cisco.ios.ios_facts
2022-05-30 14:45:43,491 p=564250 u=user n=ansible | Using module file /usr/lib/python3/dist-packages/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
2022-05-30 14:45:43,492 p=564250 u=user n=ansible | <sw-test.test.local> PUT /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/tmpoew9djoi TO /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py
2022-05-30 14:45:43,492 p=564250 u=user n=ansible | <sw-test.test.local> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/ /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py && sleep 0'
2022-05-30 14:45:43,496 p=564250 u=user n=ansible | <sw-test.test.local> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py && sleep 0'
2022-05-30 14:45:43,925 p=564257 u=user n=ansible | <sw-test.test.local> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: ctrit on PORT 22 TO sw-test.test.local
2022-05-30 14:45:44,088 p=564257 u=user n=p=564257 u=user | paramiko [sw-test.test.local] | Connected (version 2.0, client OpenSSH_7.3p1.RL)
2022-05-30 14:45:44,867 p=564257 u=user n=p=564257 u=user | paramiko [sw-test.test.local] | Authentication (publickey) successful!
2022-05-30 14:46:02,534 p=564250 u=user n=ansible | <sw-test.test.local> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/ > /dev/null 2>&1 && sleep 0'
2022-05-30 14:46:02,543 p=564245 u=user n=ansible | The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py", line 107, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=dict(_module_fqn='ansible_collections.cisco.ios.plugins.modules.ios_facts', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 254, in <module>
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py", line 246, in main
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 153, in get_facts
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 162, in get_network_legacy_facts
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/legacy/base.py", line 208, in populate
  File "/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/legacy/base.py", line 255, in populate_ipv4_interfaces
KeyError: 'IP'

2022-05-30 14:46:02,544 p=564245 u=user n=ansible | fatal: [sw-test.test.local]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-local-564245yil8i4kr/ansible-tmp-1653914743.183508-564250-123580383287863/AnsiballZ_ios_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_facts', init_globals=dict(_module_fqn='ansible_collections.cisco.ios.plugins.modules.ios_facts', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 254, in <module>\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_facts.py\", line 246, in main\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 153, in get_facts\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 162, in get_network_legacy_facts\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/legacy/base.py\", line 208, in populate\n  File \"/tmp/ansible_ios_facts_payload_tsj95rmw/ansible_ios_facts_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/legacy/base.py\", line 255, in populate_ipv4_interfaces\nKeyError: 'IP'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
2022-05-30 14:46:02,546 p=564245 u=user n=ansible | PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
2022-05-30 14:46:02,547 p=564245 u=user n=ansible | sw-test.test.local     : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2022-05-30 14:46:02,645 p=564257 u=user n=ansible | shutdown complete

```
##### Additional information
I have found an issue with an at least similar problem:  #222 
There the output of the following commands was asked:
```sw-test#show interface status                                           
                                             Flow Link          Back   Mdix  
Port     Type         Duplex  Speed Neg      ctrl State       Pressure Mode  
-------- ------------ ------  ----- -------- ---- ----------- -------- ------
gi1/0/1  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/2  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/3  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/4  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/5  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/6  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/7  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/8  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/9  1G-Copper      --      --     --     --  Down           --     --   
gi1/0/10 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/11 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/12 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/13 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/14 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/15 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/16 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/17 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/18 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/19 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/20 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/21 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/22 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/23 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/24 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/25 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/26 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/27 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/28 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/29 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/30 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/31 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/32 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/33 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/34 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/35 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/36 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/37 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/38 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/39 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/40 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/41 1G-Copper      --      --     --     --  Down           --     --   
gi1/0/42 1G-Copper      --      --     --     --  Down           --     -- 
gi1/0/43 1G-Copper      --      --     --     --  Down           --     -- 
gi1/0/44 1G-Copper      --      --     --     --  Down           --     -- 
gi1/0/45 1G-Copper      --      --     --     --  Down           --     -- 
gi1/0/46 1G-Copper      --      --     --     --  Down           --     -- 
gi1/0/47 1G-Copper    Full    1000  Enabled  Off  Up          Disabled On  
gi1/0/48 1G-Copper    Full    1000  Enabled  Off  Up          Disabled On  
te1/0/1  10G-Combo-C    --      --     --     --  Down           --     -- 
te1/0/2  10G-Combo-C    --      --     --     --  Down           --     -- 
te1/0/3  10G-Fiber    Full    10000 Disabled Off  Up          Disabled Off 
te1/0/4  10G-Fiber    Full    10000 Disabled Off  Up          Disabled Off 
                                                                           
                                          Flow    Link                     
Ch       Type    Duplex  Speed  Neg      control  State                    
-------- ------- ------  -----  -------- -------  -----------              
Po1         --     --      --      --       --    Not Present              
Po2         --     --      --      --       --    Not Present              
Po3         --     --      --      --       --    Not Present              
Po4         --     --      --      --       --    Not Present              
Po5         --     --      --      --       --    Not Present              
Po6         --     --      --      --       --    Not Present              
Po7         --     --      --      --       --    Not Present              
Po8         --     --      --      --       --    Not Present              

sw-test#show interfaces
% missing mandatory parameter

sw-test#show ip interface


    IP Address        I/F    I/F Status  Type   Directed  Prec Redirect Status
                             admin/oper         Broadcast
------------------ --------- ---------- ------- --------- ---- -------- ------
172.16.99.12/24    vlan 99   UP/UP      Static  disable   No   enable   Valid

sw-test#show ipv6 interface                                         
                                                                         
VLAN 1 is up/up                                                          
IPv6 is enabled, link-local address is fe80::5ee1:76ff:fe4d:837e         
IPv6 Forwarding is disabled                                              
No global unicast address is configured                                  
Joined group address(es):                                                
ff02::1                                                                  
ff02::1:ff4d:837e                                                        
MTU is 1500 bytes                                                        
ICMP error messages limited interval is 100ms; Bucket size is 10 tokens  
ICMP redirects are enabled                                               
ND DAD is enabled, number of DAD attempts: 1                             
ND reachable time is 30000 milliseconds                                  
ND advertised reachable time is 0 milliseconds                           
ND advertised retransmit interval is 0 milliseconds                      
ND router maximum advertisement interval is 600 seconds                  
ND router minimum advertisement interval is 198 seconds (DEFAULT)        
ND router advertisements live for 1800 seconds                           
ND advertised default router preference is medium                        
Stateless autoconfiguration is enabled                                   
MLD Version is 2                                                         
```

**Comment by KB-perByte** [comment]
Hey @lvbernus sorry for getting back at it so late.
The major reason for the facts failing with your configuration is because of how the device returns the interface configuration.
As mentioned the output of show command in your case is like
```
sw-test#show ip interface


    IP Address        I/F    I/F Status  Type   Directed  Prec Redirect Status
                             admin/oper         Broadcast
------------------ --------- ---------- ------- --------- ---- -------- ------
172.16.99.12/24    vlan 99   UP/UP      Static  disable   No   enable   Valid
```
the configuration that the facts base expects is 
```
GigabitEthernet1 is up, line protocol is up
  Internet address is 192.xxx.xxx.xx/24
  Broadcast address is 255.255.255.255
  Address determined by DHCP
  MTU is 1500 bytes
  Helper address is not set
  Directed broadcast forwarding is disabled
  Outgoing Common access list is not set 
  Outgoing access list is not set
  Inbound Common access list is not set 
  Inbound  access list is not set
  Proxy ARP is enabled
  Local Proxy ARP is disabled
  Security level is default
  Split horizon is enabled
  ICMP redirects are always sent
  ICMP unreachables are always sent
  ICMP mask replies are never sent
  IP fast switching is enabled
  IP Flow switching is disabled
  IP CEF switching is enabled
  IP CEF switching turbo vector
  IP Null turbo vector
  Associated unicast routing topologies:
        Topology "base", operation state is UP
  IP multicast fast switching is enabled
  IP multicast distributed fast switching is disabled
  IP route-cache flags are Fast, CEF
  Router Discovery is disabled
  IP output packet accounting is disabled
  IP access violation accounting is disabled
  TCP/IP header compression is disabled
  RTP/IP header compression is disabled
  Probe proxy name replies are disabled
  Policy routing is disabled
  Network address translation is disabled
  BGP Policy Mapping is disabled
  Input features: MCI Check
  IPv4 WCCP Redirect outbound is disabled
  IPv4 WCCP Redirect inbound is disabled
  IPv4 WCCP Redirect exclude is disabled
```
would you please share the appliance version that you are using? And also consider upgrading the collection version to latest.
Regards.
