### ISSUE TITLE
static routes to vlan interface gives error

### ISSUE THREAD

**Issue by darwick** [ansible-collections/cisco.ios#594]
##### SUMMARY
When I'm trying to replace an existing route where the destination is a vlan interface, then I always get an error. Checked in the router, it doesn't exists. The error from the module's stderr: `IndexError: list index out of range`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.ios.ios_static_routes module

##### ANSIBLE VERSION
```
ansible 2.10.8
  config file = /home/darwick/ansible-network/ansible.cfg
  configured module search path = ['/home/darwick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

##### COLLECTION VERSION
```
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  1.3.0 
```

##### OS / ENVIRONMENT
Client where the playbook runs: `Linux DW-LINUX 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`
Target cisco device: `Cisco IOS Software, s2t54 Software (s2t54-IPSERVICESK9-M), Version 15.1(2)SY9, RELEASE SOFTWARE (fc1)`

##### STEPS TO REPRODUCE
I just created on the device Vlan99 (also in L2 and L3) for testing. Used this piece of code to create the route entry, but I get the error back. Tried with the route (same or another) is created for the same ip, nothing works. I also tried with interface Null0 but it also does not work, the error is the same.

```yaml
- name: Add static route
  cisco.ios.ios_static_routes:
    config:
    - address_families:
      - afi: ipv4
        routes:
        - dest: "22.33.44.55/32"
          next_hops:
          - interface: "Vlan99"
    state: replaced
```

##### EXPECTED RESULTS
```
sh run | i ip route
ip route 22.33.44.55 255.255.255.255 Vlan99
```

##### ACTUAL RESULTS
```paste below
ASK [static-routing : Add static route] *******************************************************************************************************************************************************************************************************************************************************************************************************************
...
The full traceback is:
Traceback (most recent call last):
  File "/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py", line 102, in <module>
    _ansiballz_main()
  File "/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_static_routes', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py", line 692, in <module>
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py", line 687, in main
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py", line 75, in execute_module
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py", line 54, in get_static_routes_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py", line 121, in get_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 75, in populate_facts
  File "/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py", line 224, in render_config
IndexError: list index out of range
fatal: [c6500-test]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/darwick/.ansible/tmp/ansible-local-5671vpacbj0p/ansible-tmp-1654460496.6973882-5783-175988666614224/AnsiballZ_ios_static_routes.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_static_routes', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py\", line 692, in <module>\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_static_routes.py\", line 687, in main\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py\", line 75, in execute_module\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/config/static_routes/static_routes.py\", line 54, in get_static_routes_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/facts.py\", line 121, in get_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py\", line 75, in populate_facts\n  File \"/tmp/ansible_cisco.ios.ios_static_routes_payload_rqunktbo/ansible_cisco.ios.ios_static_routes_payload.zip/ansible_collections/cisco/ios/plugins/module_utils/network/ios/facts/static_routes/static_routes.py\", line 224, in render_config\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by KB-perByte** [comment]
Hey, @darwick would you please check the same issue with the latest release of the collection, the version mentioned has had quite some major updates that may fix the problem for you.
Regards

**Comment by darwick** [comment]
Hello, cisco.ios upgraded to the latest (3.1.0) and now it works. Thank you, I thought the latest Debian version has much newer collections installed, but it seems not.
