### ISSUE TITLE
ios_config: all tasks fail in loop after first change

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/cisco.ios#714]
##### SUMMARY
I'm configuring interfaces in a loop.  After the first successful change, all subsequent items in the task loop fail.  Saw with 3.0.0 and 4.2.0.  Seems similar to #651 but apparently that should be fixed in 4.2.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.3]
  config file = /home/orion-admin/ansible-network/ansible.cfg
  configured module search path = ['/home/orion-admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/orion-admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
ansible.netcommon     2.6.1  
ansible.utils         2.6.1  
ansible.windows       1.10.0 
chocolatey.chocolatey 1.4.0  
cisco.ios             4.2.0 
cisco.nxos            3.0.0  
community.general     3.8.9  
community.windows     1.10.0 
```

##### CONFIGURATION

```paste below
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
DEFAULT_FORKS(ansible-network/ansible.cfg) = 25
DEFAULT_GATHERING(ansible-network/ansible.cfg) = explicit
DEFAULT_HOST_LIST(ansible-network/ansible.cfg) = ['/home/orion-admin/ansible-network/hosts']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = ansible-network/ansible.log
DEFAULT_ROLES_PATH(ansible-network/ansible.cfg) = ['/home/orion-admin/ansible-network/roles']
INVENTORY_ENABLED(ansible-network/ansible.cfg) = ['ini']
```

##### OS / ENVIRONMENT
RHEL 8.7

##### STEPS TO REPRODUCE

```yaml
  - name: Configure interfaces
    ios_config:
      lines: "{{ interfaces_config[item] }}"
      parents: "interface {{ interface_prefix }}/{{ item }}"
      save_when: changed
      diff_against: running
      before: "default interface {{ interface_prefix }}/{{ item }}"
    loop: "{{ range(interface_range.start, interface_range.end + 1)|list }}"
    register: config
    become: yes
```

##### EXPECTED RESULTS
No failures

##### ACTUAL RESULTS
```paste below
397927 1672190644.66685: opening command with Popen()
397927 1672190644.67477: done running command with Popen()
397927 1672190644.67504: getting output with communicate()
397927 1672190644.68356: done communicating
397927 1672190644.68366: done with local.exec_command()
397927 1672190644.68379: _low_level_execute_command() done: rc=0, stdout=ansible-tmp-1672190644.6655319-397927-34362037018301=/home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301
, stderr=
redirecting (type: modules) ansible.builtin.ios_config to cisco.ios.ios_config
397927 1672190644.68606: ANSIBALLZ: using cached module: /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansiballz_cache/ansible_collections.cisco.ios.plugins.modules.ios_config-ZIP_DEFLATED
397927 1672190644.68645: variable 'ansible_playbook_python' from source: magic vars
Using module file /usr/share/ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_config.py
397927 1672190644.68713: transferring module to remote /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py
<sw-cisco-2960s-48p-1.mry.nwra.com> PUT /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/tmp31hcjokp TO /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py
397927 1672190644.68831: done transferring module to remote
397927 1672190644.68854: _low_level_execute_command(): starting
397927 1672190644.68866: _low_level_execute_command(): executing: /bin/sh -c 'chmod u+x /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/ /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py && sleep 0'
397927 1672190644.68873: in local.exec_command()
<sw-cisco-2960s-48p-1.mry.nwra.com> EXEC /bin/sh -c 'chmod u+x /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/ /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py && sleep 0'
397927 1672190644.68895: opening command with Popen()
397927 1672190644.69563: done running command with Popen()
397927 1672190644.69587: getting output with communicate()
397927 1672190644.69914: done communicating
397927 1672190644.69926: done with local.exec_command()
397927 1672190644.69937: _low_level_execute_command() done: rc=0, stdout=, stderr=
397927 1672190644.69944: _low_level_execute_command(): starting
397927 1672190644.69970: _low_level_execute_command(): executing: /bin/sh -c '/usr/bin/python3.9 /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py && sleep 0'
397927 1672190644.69980: in local.exec_command()
<sw-cisco-2960s-48p-1.mry.nwra.com> EXEC /bin/sh -c '/usr/bin/python3.9 /home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py && sleep 0'
397927 1672190644.70021: opening command with Popen()
397927 1672190644.70636: done running command with Popen()
397927 1672190644.70659: getting output with communicate()
397927 1672190647.85281: done communicating
397927 1672190647.85311: done with local.exec_command()
397927 1672190647.85342: _low_level_execute_command() done: rc=1, stdout=, stderr=Traceback (most recent call last):
  File "/home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py", line 107, in <module>
    _ansiballz_main()
  File "/home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/orion-admin/.ansible/tmp/ansible-local-397902jcp2i7fb/ansible-tmp-1672190644.6655319-397927-34362037018301/AnsiballZ_ios_config.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.ios.plugins.modules.ios_config', init_globals=dict(_module_fqn='ansible_collections.cisco.ios.plugins.modules.ios_config', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ios_config_payload_88oi0ioy/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py", line 578, in <module>
  File "/tmp/ansible_ios_config_payload_88oi0ioy/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py", line 506, in main
  File "/tmp/ansible_ios_config_payload_88oi0ioy/ansible_ios_config_payload.zip/ansible_collections/cisco/ios/plugins/modules/ios_config.py", line 390, in edit_config_or_macro
  File "/tmp/ansible_ios_config_payload_88oi0ioy/ansible_ios_config_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: dot1x timeout tx-period 8
dot1x timeout tx-period 8
  ^
% Invalid input detected at '^' marker.

sw-cisco-2960s-48p-1(config-if)#
```

**Comment by opoplawski** [comment]
It seems to work if I get rid of the `before:` option.  That also fixes the diff output.  With `before:` it appears to do a diff from after the before command is run - i.e. it shows all of configuration options, not just the ones changed.

**Comment by opoplawski** [comment]
Okay, I think I see what's going on.  I'm using `before:` to clear the interface, expecting ios_config to apply the full config to the interface.  But instead it is only applying the line that differs from the current config, which in this case is `dot1x timeout tx-period 8`, and which cannot be applied to an empty interface configuration.

Looks like I needed to add `replace: block` to get my intended effect.  This has the slightly unfortunate effect of making `updates:` return the full set of commands, but I can live with that.  At least the `diff:` output is correct.
