### ISSUE TITLE
No existing connection

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.ios#843]
Suddenly I have started experiencing problems running plays toward a certain Cisco switch model:

```
Switch Ports Model                     SW Version            SW Image
------ ----- -----                     ----------            ----------
*    1 30    WS-C3560X-24              15.2(4)E10            C3560E-UNIVERSALK9-M
```
This has not been any problem before, but now I get this when running towards them:

```
fatal: [switch1]: FAILED! => changed=false
  msg: No existing session
```
It does not matter which modules I try, or even just gather facts.
I've tried defining this in ansible.cfg, but no dice:

```
 [persistent_connection]
  connect_timeout = 60
  command_timeout = 60
```

I've tried both downgrading cisco.ios to 4.5.0 and ansible.netcommon to 5.1.0, but that did not help either.

Edit:
When running to alot of devices (>100) I can see that the 'no existing session' error can occur towards cisco 9k switches aswell, but this is not consistent. It is consistent against the 3560X switches.

**Comment by KB-perByte** [comment]
Hey @jorgenspange could you share the persistent logs from your execution [ref](https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#enabling-networking-logging-and-how-to-read-the-logfile)
Regards

**Comment by jorgenspange** [comment]
@KB-perByte Here you go!

````
2023-06-14 15:22:23,324 p=13644 u=whoami n=ansible | ansible-playbook [core 2.15.0]
  config file = /Users/whoami/Documents/ansible-network-automation/ansible.cfg
  configured module search path = ['/Users/whoami/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/whoami/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.11.4 (main, Jun  7 2023, 00:34:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
2023-06-14 15:22:23,324 p=13644 u=whoami n=ansible | Using /Users/whoami/Documents/ansible-network-automation/ansible.cfg as config file
2023-06-14 15:22:23,330 p=13644 u=whoami n=ansible | setting up inventory plugins
2023-06-14 15:22:23,376 p=13644 u=whoami n=ansible | Loading collection ansible.builtin from 
2023-06-14 15:22:23,421 p=13644 u=whoami n=ansible | Skipping empty key (hosts) in group (DISTRIBUTION_IOS)
2023-06-14 15:22:23,441 p=13644 u=whoami n=ansible | Parsed /Users/whoami/Documents/ansible-network-automation/inventory/NETWORK2/campus.yml inventory source with yaml plugin
2023-06-14 15:22:23,441 p=13644 u=whoami n=ansible | setting up inventory plugins
2023-06-14 15:22:23,443 p=13644 u=whoami n=ansible | Skipping empty key (hosts) in group (SPINE_NXOS)
2023-06-14 15:22:23,443 p=13644 u=whoami n=ansible | Skipping empty key (hosts) in group (LEAF_NXOS)
2023-06-14 15:22:23,444 p=13644 u=whoami n=ansible | Parsed /Users/whoami/Documents/ansible-network-automation/inventory/NETWORK2/datacenter.yml inventory source with yaml plugin
2023-06-14 15:22:23,444 p=13644 u=whoami n=ansible | setting up inventory plugins
2023-06-14 15:22:23,446 p=13644 u=whoami n=ansible | Skipping empty key (hosts) in group (MGT_NXOS)
2023-06-14 15:22:23,446 p=13644 u=whoami n=ansible | Parsed /Users/whoami/Documents/ansible-network-automation/inventory/NETWORK2/management.yml inventory source with yaml plugin
2023-06-14 15:22:23,446 p=13644 u=whoami n=ansible | setting up inventory plugins
2023-06-14 15:22:23,448 p=13644 u=whoami n=ansible | Skipping empty key (hosts) in group (ROUTER_IOSXR)
2023-06-14 15:22:23,449 p=13644 u=whoami n=ansible | Parsed /Users/whoami/Documents/ansible-network-automation/inventory/NETWORK2/routers.yml inventory source with yaml plugin
2023-06-14 15:22:23,734 p=13644 u=whoami n=ansible | Loading collection cisco.ios from /Users/whoami/.ansible/collections/ansible_collections/cisco/ios
2023-06-14 15:22:23,734 p=13644 u=whoami n=ansible | redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
2023-06-14 15:22:23,777 p=13644 u=whoami n=ansible | redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
2023-06-14 15:22:23,809 p=13644 u=whoami n=ansible | Loading collection community.general from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible_collections/community/general
2023-06-14 15:22:23,809 p=13644 u=whoami n=ansible | redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
2023-06-14 15:22:23,812 p=13644 u=whoami n=ansible | Loading callback plugin community.general.yaml of type stdout, v2.0 from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible_collections/community/general/plugins/callback/yaml.py
2023-06-14 15:22:23,821 p=13644 u=whoami n=ansible | Skipping callback 'default', as we already have a stdout callback.
2023-06-14 15:22:23,821 p=13644 u=whoami n=ansible | Skipping callback 'minimal', as we already have a stdout callback.
2023-06-14 15:22:23,821 p=13644 u=whoami n=ansible | Skipping callback 'oneline', as we already have a stdout callback.
2023-06-14 15:22:23,839 p=13644 u=whoami n=ansible |  __________________________________ 
< PLAYBOOK: playbook_ios_facts.yml >
 ---------------------------------- 
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *


2023-06-14 15:22:23,840 p=13644 u=whoami n=ansible | 1 plays in playbook_ios_facts.yml
2023-06-14 15:22:23,872 p=13644 u=whoami n=ansible |  _________________________ 
< PLAY [gather ios facts] >
 ------------------------- 
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *


2023-06-14 15:22:23,889 p=13644 u=whoami n=ansible | redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
2023-06-14 15:22:23,891 p=13644 u=whoami n=ansible | Loading collection ansible.netcommon from /Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon
2023-06-14 15:22:23,898 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,905 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,910 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,915 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,931 p=13644 u=whoami n=ansible | Loading collection ansible.utils from /Users/whoami/.ansible/collections/ansible_collections/ansible/utils
2023-06-14 15:22:23,945 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,950 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,957 p=13644 u=whoami n=ansible | Trying secret FileVaultSecret(filename='/Users/whoami/Documents/ansible-network-automation/.secret/vault_pass.txt') for vault_id=default
2023-06-14 15:22:23,962 p=13644 u=whoami n=ansible | <192.168.10.51> attempting to start connection
2023-06-14 15:22:23,962 p=13644 u=whoami n=ansible | <192.168.10.51> using connection plugin ansible.netcommon.network_cli
2023-06-14 15:22:23,962 p=13644 u=whoami n=ansible | Found ansible-connection at path /opt/homebrew/bin/ansible-connection
2023-06-14 15:22:24,336 p=13654 u=whoami n=ansible | Loading collection ansible.builtin from 
2023-06-14 15:22:24,388 p=13659 u=whoami n=ansible | Loading collection ansible.netcommon from /Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon
2023-06-14 15:22:24,398 p=13659 u=whoami n=ansible | Loading collection ansible.utils from /Users/whoami/.ansible/collections/ansible_collections/ansible/utils
2023-06-14 15:22:24,408 p=13659 u=whoami n=ansible | Loading collection cisco.ios from /Users/whoami/.ansible/collections/ansible_collections/cisco/ios
2023-06-14 15:22:25,063 p=13644 u=whoami n=ansible | <192.168.10.51> local domain socket does not exist, starting it
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51> control socket path is /Users/whoami/.ansible/pc/122533e721
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51> Loading collection ansible.builtin from 
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.33844: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.33859: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.34779: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments
2023-06-14 15:22:25,064 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.34828: Loading ModuleDocFragment 'connection_pipelining' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py
2023-06-14 15:22:25,067 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.34844: Loaded config def from plugin (connection/ssh)
2023-06-14 15:22:25,068 p=13644 u=whoami n=ansible | <192.168.10.51>  13654 1686748944.34845: Loading Connection 'ssh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/ssh.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection) (found_in_cache=False, class_only=True)
2023-06-14 15:22:25,068 p=13644 u=whoami n=ansible | <192.168.10.51> Loading collection ansible.netcommon from /Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon
2023-06-14 15:22:25,068 p=13644 u=whoami n=ansible | <192.168.10.51> Loading collection ansible.utils from /Users/whoami/.ansible/collections/ansible_collections/ansible/utils
2023-06-14 15:22:25,068 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40249: Loading ModuleDocFragment 'ansible_collections.ansible.netcommon.plugins.doc_fragments.connection_persistent' from /Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/doc_fragments/connection_persistent.py
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40281: Loaded config def from plugin (connection/ansible_collections.ansible.netcommon.plugins.connection.network_cli)
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40283: Loading Connection 'ansible_collections.ansible.netcommon.plugins.connection.network_cli' from /Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection)
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40367: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40484: Loading ModuleDocFragment 'shell_common' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments/shell_common.py
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40536: Loaded config def from plugin (shell/sh)
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40536: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40538: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,069 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40595: Loading ModuleDocFragment 'connection_pipelining' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40607: Loaded config def from plugin (connection/local)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40608: Loading Connection 'local' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/local.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40610: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40611: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.40624: Loading Connection 'ssh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/ssh.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection) (found_in_cache=True, class_only=True)
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51> Loading collection cisco.ios from /Users/whoami/.ansible/collections/ansible_collections/cisco/ios
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41190: Loading TerminalModule 'ansible_collections.cisco.ios.plugins.terminal.ios' from /Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/terminal/ios.py
2023-06-14 15:22:25,070 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41682: Loaded config def from plugin (cliconf/ansible_collections.cisco.ios.plugins.cliconf.ios)
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41683: Loading Cliconf 'ansible_collections.cisco.ios.plugins.cliconf.ios' from /Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41906: Loaded config def from plugin (connection/paramiko_ssh)
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41907: Loading Connection 'paramiko_ssh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/paramiko_ssh.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection)
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41909: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51>  13659 1686748944.41910: Loading ShellModule 'sh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51> local domain socket listeners started successfully
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | <192.168.10.51> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
2023-06-14 15:22:25,071 p=13644 u=whoami n=ansible | network_os is set to cisco.ios.ios
2023-06-14 15:22:25,072 p=13644 u=whoami n=ansible | <192.168.10.51> ssh type is set to paramiko
2023-06-14 15:22:25,072 p=13644 u=whoami n=ansible | <192.168.10.51> Loading collection ansible.builtin from 
 13654 1686748944.33844: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__
 13654 1686748944.33859: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection
 13654 1686748944.34779: trying /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments
 13654 1686748944.34828: Loading ModuleDocFragment 'connection_pipelining' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/doc_fragments/connection_pipelining.py
 13654 1686748944.34844: Loaded config def from plugin (connection/ssh)
 13654 1686748944.34845: Loading Connection 'ssh' from /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/ssh.py (searched paths: /opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/__pycache__:/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection) (found_in_cache=False, class_only=True)

2023-06-14 15:22:25,072 p=13644 u=whoami n=ansible | <192.168.10.51> local domain socket path is /Users/whoami/.ansible/pc/122533e721
2023-06-14 15:22:25,082 p=13644 u=whoami n=ansible | redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
2023-06-14 15:22:25,082 p=13644 u=whoami n=ansible | redirecting (type: action) cisco.ios.ios_facts to cisco.ios.ios
2023-06-14 15:22:25,084 p=13644 u=whoami n=ansible | <192.168.10.51> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
2023-06-14 15:22:25,282 p=13644 u=whoami n=ansible | <192.168.10.51> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.ios.ios_facts  at /Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_facts.py
2023-06-14 15:22:25,282 p=13644 u=whoami n=ansible | <192.168.10.51> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.ios.ios_facts
2023-06-14 15:22:25,282 p=13659 u=whoami n=ansible | [DEPRECATION WARNING]: PlayContext.verbosity is deprecated, use 
ansible.utils.display.Display.verbosity instead. This feature will be removed 
in version 2.18. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
2023-06-14 15:22:25,283 p=13659 u=whoami n=ansible | <192.168.10.51> ESTABLISH PARAMIKO SSH CONNECTION FOR USER: psad06871 on PORT 22 TO 192.168.10.51
2023-06-14 15:22:25,285 p=13659 u=whoami n=ansible | <192.168.10.51> CONFIGURE PROXY COMMAND FOR CONNECTION: ssh -W 192.168.10.51:22 -q adad06871@10.182.30.9
2023-06-14 15:22:35,392 p=13659 u=whoami n=ansible | Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 498, in _connect_uncached
    ssh.connect(
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/paramiko/client.py", line 457, in connect
    server_key = t.get_remote_server_key()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/paramiko/transport.py", line 902, in get_remote_server_key
    raise SSHException("No existing session")
paramiko.ssh_exception.SSHException: No existing session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/utils/jsonrpc.py", line 46, in handle_request
    result = rpc_method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 475, in get_capabilities
    result = super(Cliconf, self).get_capabilities()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/plugin_utils/cliconf_base.py", line 318, in get_capabilities
    result["device_info"] = self.get_device_info()
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whoami/.ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 421, in get_device_info
    self._update_cli_prompt_context(config_context=")#", exit_command="end")
  File "/Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/plugin_utils/cliconf_base.py", line 532, in _update_cli_prompt_context
    out = self._connection.get_prompt()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 339, in wrapped
    self._connect()
  File "/Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 639, in _connect
    ssh = self.ssh_type_conn._connect()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 380, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 524, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
ansible.errors.AnsibleConnectionFailure: No existing session

2023-06-14 15:22:35,394 p=13644 u=whoami n=ansible | <192.168.10.51> ANSIBLE_NETWORK_IMPORT_MODULES: complete
2023-06-14 15:22:35,420 p=13644 u=whoami n=ansible |  _________________________ 
< TASK [Gather ios facts] >
 ------------------------- 
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *


2023-06-14 15:22:35,420 p=13644 u=whoami n=ansible | The full traceback is:
  File "/Users/whoami/.ansible/collections/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/network.py", line 233, in get_capabilities
    capabilities = Connection(module._socket_path).get_capabilities()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/8.0.0/libexec/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

2023-06-14 15:22:35,420 p=13644 u=whoami n=ansible | fatal: [switch_hostname]: FAILED! => changed=false 
  invocation:
    module_args:
      available_network_resources: false
      gather_network_resources: null
      gather_subset:
      - min
  msg: No existing session
2023-06-14 15:22:35,442 p=13644 u=whoami n=ansible |  ____________ 
< PLAY RECAP >
 ------------ 
       \   ,__,
        \  (oo)____
           (__)    )\
              ||--|| *


2023-06-14 15:22:35,443 p=13644 u=whoami n=ansible | switch_hostname                : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2023-06-14 15:22:35,524 p=13659 u=whoami n=ansible | shutdown complete

````

**Comment by KB-perByte** [comment]
CC @Qalthos ^

**Comment by KB-perByte** [comment]
@jorgenspange would you try using `ansible_network_cli_ssh_type=libssh`?
Regards

**Comment by jorgenspange** [comment]
Does not exist for macos, unfortunately.. But I agree I think this is a paramiko issue.

**Comment by Qalthos** [comment]
> Does not exist for macos, unfortunately.. But I agree I think this is a paramiko issue.

[`ansible-pylibssh`](https://pypi.org/project/ansible-pylibssh/) has x86_64 wheels for Python 3.6 through 3.10 and a universal wheel for 3.11. I don't have the hardware to use them myself, but is there something missing there that we need to add?

**Comment by jorgenspange** [comment]
@Qalthos Hi, I am not really familiar with these kind of things, but I think you have to release a separate wheel for M1/M2/apple silicon (macos ARM64) if i’m not mistaking

**Comment by jorgenspange** [comment]
The preferred way to install packages on macos is with brew? Would it be possible to make it available there? @Qalthos

**Comment by KB-perByte** [comment]
Hey @jorgenspange I see some successful installation steps [here](https://stackoverflow.com/questions/74048675/cannot-install-ansible-pylibssh-on-macos) Would you give it a try?
Regards

**Comment by jorgenspange** [comment]
Hey @KB-perByte 

Managed to install it, but still no dice when running the play:

````
failed: [switch1] (item=login) => changed=false
  ansible_loop_var: item
  item: login
  msg: Failed to import the required Python library (ansible-pylibssh) on Jorgens-MBP.local's Python /opt/homebrew/Cellar/ansible/8.0.0/libexec/bin/python3.11. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter
failed: [switch1] (item=exec) => changed=false
````
Even tried specifing the interpreter in the inventory:

````
(.venv) [jorgenspange@Jorgens-MBP Documents/ansible-network-automation (main) ]$ which python
/Users/jorgenspange/Documents/ansible-network-automation/.venv/bin/python
````
````
 ansible_python_interpreter: /Users/jorgenspange/Documents/ansible-network-automation/.venv/bin/python
````

**Comment by jorgenspange** [comment]
Update, after reinstalling ansible paramiko is now working towards most of the hosts, but I am still having the same problem towards the 3560 switches.

**Comment by jorgenspange** [comment]
Finally got ansible-pylibssh to work, by installing it this way:

````
export CFLAGS="-I$(brew --prefix)/include"
export LIBRARY_PATH="$(brew --prefix)/lib"
pip install ansible-pylibssh --global-option=build_ext --global-option="-I$(brew --prefix)/include" --global-option="-L$(brew --prefix)/lib"
````
But seems like libssh does not support old KexAlgorithms:
````
fatal: [switch1]: FAILED! => changed=false
  msg: 'ssh connection failed: ssh connect failed: kex error : no match for method kex algos: server [diffie-hellman-group-exchange-sha1], client [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256]'
````

Best regards

**Comment by jorgenspange** [comment]
Okey, so thanks for all the support. Closing this issue as i dont think the cisco.ios module is the problem.
The whole problem seems very random and could be related to other things.

Thanks again for the support and sorry for the hassle.

Best regards
