### ISSUE TITLE
Internal error on "show run"

### ISSUE THREAD

**Issue by rowco** [ansible-collections/cisco.ios#889]
##### SUMMARY

I have a playbook which captures a "show run" and on some devices it fails every time with an Internal error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.ios.ios_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.1]
  config file = /home/xxx/global-comms-ansible/ansible.cfg
  configured module search path = ['/home/xxx/global-comms-ansible/library']
  ansible python module location = /home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/xxx/global-comms-ansible/collections
  executable location = /home/xxx/virtualenvs/ansible-base/bin/ansible
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/xxx/virtualenvs/ansible-base/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/xxx/global-comms-ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.ios  *      

# /home/xxx/virtualenvs/ansible-base/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.6.1  

# /home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
cisco.ios  4.6.1 
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/collections']
CONFIG_FILE() = /home/xxx/global-comms-ansible/ansible.cfg
DEFAULT_ALLOW_UNSAFE_LOOKUPS(/home/xxx/global-comms-ansible/ansible.cfg) = True
DEFAULT_CLICONF_PLUGIN_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/plugins/cliconf']
DEFAULT_FILTER_PLUGIN_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/filter_plugins']
DEFAULT_FORKS(/home/xxx/global-comms-ansible/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/inventory/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/xxx/global-comms-ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = /home/xxx/global-comms-ansible/ansible.log
DEFAULT_MODULE_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/library']
DEFAULT_MODULE_UTILS_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/filter_plugins']
DEFAULT_ROLES_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/roles']
DEFAULT_TERMINAL_PLUGIN_PATH(/home/xxx/global-comms-ansible/ansible.cfg) = ['/home/xxx/global-comms-ansible/plugins/terminal']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/xxx/global-comms-ansible/vault_id
DISPLAY_SKIPPED_HOSTS(/home/xxx/global-comms-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/xxx/global-comms-ansible/ansible.cfg) = False
INJECT_FACTS_AS_VARS(/home/xxx/global-comms-ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/xxx/global-comms-ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'netbox.netbox.nb_inventory']
MAX_FILE_SIZE_FOR_DIFF(/home/xxx/global-comms-ansible/ansible.cfg) = 5000000
```

##### OS / ENVIRONMENT

Model Number                       : C9500-24Y4C  
Cisco IOS XE Software, Version 17.06.01

##### STEPS TO REPRODUCE

Very simple playbook.

```yaml

    - name: fetch show run
      cisco.ios.ios_command:
        commands: show run
      register: output
      become: yes
```

##### EXPECTED RESULTS

On all other devices this runs fine and returns the running config.

##### ACTUAL RESULTS

```paste below
2023-07-14 12:44:18,297 p=1797310 u=xxx n=ansible | Traceback (most recent call last):
  File "/home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible/utils/jsonrpc.py", line 46, in handle_request
    result = rpc_method(*args, **kwargs)
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py", line 417, in run_commands
    out = self.send_command(**cmd)
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon/plugins/plugin_utils/cliconf_base.py", line 146, in send_command
    resp = self._connection.send(**kwargs)
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 341, in wrapped
    return func(self, *args, **kwargs)
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 1063, in send
    response = self.receive(
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 1012, in receive
    response = self.receive_paramiko(
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 871, in receive_paramiko
    raise AnsibleConnectionFailure(errored_response)
ansible.errors.AnsibleConnectionFailure: ttern ".*61504.*Threshold below for mos"
 action 1.0 syslog priority notifications msg "IP-SLA MOS ERROR: CORE WAN - xxx to xxx MOS UNDER 3.5"
event manager applet IP-SLA-61504-MOS-RESTORE
 event syslog occurs 1 pattern ".*61504.*Thres

2023-07-14 12:44:18,309 p=1797244 u=xxx n=ansible | <xxx> ANSIBLE_NETWORK_IMPORT_MODULES: complete
2023-07-14 12:44:18,311 p=1797244 u=xxx n=ansible | TASK [fetch show run] **************************************************************************************************************************************************************************************************
2023-07-14 12:44:18,315 p=1797244 u=xxx n=ansible | The full traceback is:
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 141, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(response)

2023-07-14 12:44:18,315 p=1797244 u=xxx n=ansible | fatal: [xxx]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show run"
            ],
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "{'jsonrpc': '2.0', 'id': '34618fa7-11a7-451c-876c-57cd949e28dc', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'ttern \".*61504.*Threshold below for mos\"\\r\\n action 1.0 syslog priority
 notifications msg \"IP-SLA MOS ERROR: CORE WAN - xxx to xxx  MOS UNDER 3.5\"\\r\\nevent manager applet IP-SLA-61504-MOS-RESTORE\\r\\n event syslog occurs 1 pattern \".*61504.*Thres'}}"
}
```

**Comment by rowco** [comment]
Hi @KB-perByte, 

Any thoughts on this? Can I get you any more information to help diagnose?

**Comment by KB-perByte** [comment]
Hey @rowco would you try to use the default ssh type, `ansible_network_cli_ssh_type=libssh`? 
Regards

**Comment by rowco** [comment]
Hey. I did actually try this before, and just tested again. I get the same result, but with more output, it shows the entire running config before failing. (I've snipped out some of the output for privicy).

`ansible-playbook [core 2.15.1]
  config file = /home/xxx/global-comms-ansible/ansible.cfg
  configured module search path = ['/home/xxx/global-comms-ansible/library']
  ansible python module location = /home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/xxx/global-comms-ansible/collections
  executable location = /home/xxx/virtualenvs/ansible-base/bin/ansible-playbook
  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/xxx/virtualenvs/ansible-base/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
Using /home/xxx/global-comms-ansible/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from 
Loading collection netbox.netbox from /home/xxx/global-comms-ansible/collections/ansible_collections/netbox/netbox
host_list declined parsing /home/xxx/global-comms-ansible/inventory/inventory as it did not pass its verify_file() method
script declined parsing /home/xxx/global-comms-ansible/inventory/inventory as it did not pass its verify_file() method
auto declined parsing /home/xxx/global-comms-ansible/inventory/inventory as it did not pass its verify_file() method
Parsed /home/xxx/global-comms-ansible/inventory/inventory inventory source with ini plugin
Trying secret FileVaultSecret(filename='/home/xxx/global-comms-ansible/vault_id') for vault_id=default
Loading collection cisco.ios from /home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
Loading callback plugin default of type stdout, v2.0 from /home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: debug.yml ********************************************************************************************************************************************************************************************************************
Positional arguments: playbooks/ops/debug.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/home/xxx/global-comms-ansible/inventory/inventory',)
subset: gbcorolwpe12
forks: 30
1 plays in playbooks/ops/debug.yml

PLAY [Run a connectivity test] *********************************************************************************************************************************************************************************************************
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
Loading collection ansible.netcommon from /home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
Loading collection ansible.utils from /home/xxx/global-comms-ansible/collections/ansible_collections/ansible/utils
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<gbcorolwpe12> attempting to start connection
<gbcorolwpe12> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /home/xxx/virtualenvs/ansible-base/bin/ansible-connection
<gbcorolwpe12> local domain socket does not exist, starting it
<gbcorolwpe12> control socket path is /home/xxx/.ansible/pc/d5f06b7156
<gbcorolwpe12> Loading collection ansible.builtin from 
<gbcorolwpe12> redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
<gbcorolwpe12> Loading collection ansible.netcommon from /home/xxx/global-comms-ansible/collections/ansible_collections/ansible/netcommon
<gbcorolwpe12> Loading collection ansible.utils from /home/xxx/global-comms-ansible/collections/ansible_collections/ansible/utils
<gbcorolwpe12> Loading collection cisco.ios from /home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios
<gbcorolwpe12> local domain socket listeners started successfully
<gbcorolwpe12> loaded cliconf plugin ansible_collections.cisco.ios.plugins.cliconf.ios from path /home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios/plugins/cliconf/ios.py for network_os cisco.ios.ios
<gbcorolwpe12> ssh type is set to libssh
<gbcorolwpe12> Loading collection ansible.builtin from 
<gbcorolwpe12> local domain socket path is /home/xxx/.ansible/pc/d5f06b7156
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
redirecting (type: action) cisco.ios.ios_command to cisco.ios.ios
<gbcorolwpe12> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
<gbcorolwpe12> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.ios.ios_command  at /home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios/plugins/modules/ios_command.py
<gbcorolwpe12> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.ios.ios_command
<gbcorolwpe12> ANSIBLE_NETWORK_IMPORT_MODULES: complete

TASK [fetch show run] ******************************************************************************************************************************************************************************************************************
task path: /home/xxx/global-comms-ansible/playbooks/ops/debug.yml:14
The full traceback is:
  File "/home/xxx/global-comms-ansible/collections/ansible_collections/cisco/ios/plugins/module_utils/network/ios/ios.py", line 105, in run_commands
    return connection.run_commands(commands=commands, check_rc=check_rc)
  File "/home/xxx/virtualenvs/ansible-base/lib64/python3.9/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(response)
fatal: [gbcorolwpe12]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                "show run"
            ],
            "interval": 1,
            "match": "all",
            "retries": 9,
            "wait_for": null
        }
    },
    "msg": "{'jsonrpc': '2.0', 'id': 'c0133403-b24f-4889-91fc-ae89b2b8c977', 'error': {'code': -32603, 'message': 'Internal error', 'data': 'show run\\r\\nBuilding configuration...
    
    <SNIP>

    event manager applet IP-SLA-61504-RTT-HIGH\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold exceeded for rtt\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA RTT ERROR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 RTT ABOVE 11ms\"\\r\\nevent manager applet IP-SLA-61504-RTT-RESTORE\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold below for rtt\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA RTT CLEAR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 RTT UNDER 6ms\"\\r\\nevent manager applet IP-SLA-61504-JITTER-HIGH\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold exceeded for jitterAvg\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA JITTER ERROR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 JITTER ABOVE 5ms\"\\r\\nevent manager applet IP-SLA-61504-JITTER-RESTORE\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold below for jitterAvg\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA JITTER CLEAR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 JITTER UNDER 3ms\"\\r\\nevent manager applet IP-SLA-61504-MOS-HIGH\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold below for mos\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA MOS ERROR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 MOS UNDER 3.5\"\\r\\nevent manager applet IP-SLA-61504-MOS-RESTORE\\r\\n event syslog occurs 1 pattern \".*61504.*Threshold exceeded for mos\"\\r\\n action 1.0 syslog priority notifications msg \"IP-SLA MOS CLEAR: CORE WAN - GBCOROLWPE12 to GBCORENFPE12 MOS ABOVE 4\"\\r\\n!\\r\\nend\\r\\n\\r\\nGBCOROLWPE12#'}}"
}`

**Comment by rowco** [comment]
My best guess is that there is something about the eem script config, which is making the output end prematurely. 

example config:

```
event manager applet IP-SLA-62601-RTT-HIGH
 event syslog occurs 1 pattern ".*62601.*Threshold exceeded for rtt"
 action 1.0 syslog priority notifications msg "IP-SLA RTT ERROR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 RTT ABOVE 11ms"
event manager applet IP-SLA-62601-RTT-RESTORE
 event syslog occurs 1 pattern ".*62601.*Threshold below for rtt"
 action 1.0 syslog priority notifications msg "IP-SLA RTT CLEAR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 RTT UNDER 6ms"
event manager applet IP-SLA-62601-JITTER-HIGH
 event syslog occurs 1 pattern ".*62601.*Threshold exceeded for jitterAvg"
 action 1.0 syslog priority notifications msg "IP-SLA JITTER ERROR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 JITTER ABOVE 5ms"
event manager applet IP-SLA-62601-JITTER-RESTORE
 event syslog occurs 1 pattern ".*62601.*Threshold below for jitterAvg"
 action 1.0 syslog priority notifications msg "IP-SLA JITTER CLEAR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 JITTER UNDER 3ms"
event manager applet IP-SLA-62601-MOS-HIGH
 event syslog occurs 1 pattern ".*62601.*Threshold below for mos"
 action 1.0 syslog priority notifications msg "IP-SLA MOS ERROR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 MOS UNDER 3.5"
event manager applet IP-SLA-62601-MOS-RESTORE
 event syslog occurs 1 pattern ".*62601.*Threshold exceeded for mos"
 action 1.0 syslog priority notifications msg "IP-SLA MOS CLEAR: CORE WAN - SGCORCYXPE22 to SGCORNTTPE22 MOS ABOVE 4"
event manager applet IP-SLA-62701-RTT-HIGH
 event syslog occurs 1 pattern ".*62701.*Threshold exceeded for rtt"
 action 1.0 syslog priority notifications msg "IP-SLA RTT ERROR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 RTT ABOVE 11ms"
event manager applet IP-SLA-62701-RTT-RESTORE
 event syslog occurs 1 pattern ".*62701.*Threshold below for rtt"
 action 1.0 syslog priority notifications msg "IP-SLA RTT CLEAR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 RTT UNDER 6ms"
event manager applet IP-SLA-62701-JITTER-HIGH
 event syslog occurs 1 pattern ".*62701.*Threshold exceeded for jitterAvg"
 action 1.0 syslog priority notifications msg "IP-SLA JITTER ERROR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 JITTER ABOVE 5ms"
event manager applet IP-SLA-62701-JITTER-RESTORE
 event syslog occurs 1 pattern ".*62701.*Threshold below for jitterAvg"
 action 1.0 syslog priority notifications msg "IP-SLA JITTER CLEAR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 JITTER UNDER 3ms"
event manager applet IP-SLA-62701-MOS-HIGH
 event syslog occurs 1 pattern ".*62701.*Threshold below for mos"
 action 1.0 syslog priority notifications msg "IP-SLA MOS ERROR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 MOS UNDER 3.5"
event manager applet IP-SLA-62701-MOS-RESTORE
 event syslog occurs 1 pattern ".*62701.*Threshold exceeded for mos"
 action 1.0 syslog priority notifications msg "IP-SLA MOS CLEAR: CORE WAN - SGCORNTTPE21 to SGCORSG4PE21 MOS ABOVE 4"
```

**Comment by rowco** [comment]
Right, if I run the following, it works as expected:

```
    - name: fetch show run
      cisco.ios.ios_command:
        commands: show run **| exclude action**
      register: output
      become: yes
```

**Comment by rowco** [comment]
@KB-perByte - please let me know if there is anything else I can provide.

**Comment by KB-perByte** [comment]
@rowco You did the hard part identifying the issue. Let me check if there can be ways to bypass it somehow by enforcing the err regexes to not pick it up maybe.
Regards

**Comment by rowco** [comment]
@KB-perByte  Ok, worked through the regexes in terminal/ios.py. 

Looks like the config is hitting the following:

` re.compile(rb"[%\S] ?Error: ?[\s]+", re.I),`

I think this is too open as will trigger for any string 'xxx error:'. I suggest moving to:

`re.compile(rb"% ?(\S+) ?Error: ?[\s]+", re.I),`

Shall I raise a PR?

**Comment by KB-perByte** [comment]
Hey @rowco, That is correct, the exact regex picks up the config as an error from the output and reports a failure.
I don't recommend changing it as it might encounter False positives at some other places.
Well, the advised way is to override the error regexes on the play level with `ansible_terminal_stderr_re`, in the playbook itself ref: [ansible_terminal_stderr_re](https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#task-failure-due-to-mismatched-error-regex-within-command-response-using-ansible-netcommon-network-cli-connection-type)

Regards.

**Comment by KB-perByte** [comment]
@rowco I took some time looking into it, we can add the regex you recommended.
You may raise a PR with that. I'll be happy to review it.
Thanks for the brainstorming. Appreciate it. 
Regards
